#!/usr/bin/env python3
"""資料庫全面擴充：分批把新型號寫入 data/new_items_extra.json（依 id 去重、可累加）。
每批以精簡欄位定義，mk() 補上完整結構。諸元為公開資料整理，wiki 供後續抓圖/查證。"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "new_items_extra.json"

def W(title, zh=None):
    return [{"label": f"維基百科：{zh or title}", "url": f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"}]

def mk(id, zh, en, desig, sub, svc, *, cat="vehicle", aliases=None, caliber="—", crew="—",
       weight="—", length="—", rng="—", cap="—", mob="—", sensors="—", armor="—",
       notes="", tags=None, form_zh="", wiki="", sources=None, image=""):
    return {
        "id": id, "name_zh": zh, "name_en": en, "designation": desig,
        "aliases": aliases or [], "category": cat, "subcategory": sub,
        "origin": "China", "origin_zh": "中國", "service": svc, "service_zh": svc,
        "caliber": caliber, "crew": crew, "weight_kg": weight, "length_mm": length,
        "range_m": rng, "rate_of_fire": "—", "capacity": cap, "armor": armor,
        "mobility": mob, "sensors": sensors, "notes_zh": notes, "notes_en": "",
        "tags": tags or [], "odin_hint": "", "form_zh": form_zh, "form_en": "",
        "wiki": wiki, "image": image, "odin_url": "https://odin.t2com.army.mil/WEG",
        "sources": sources or (W(wiki) if wiki else []),
    }

# ===== 批次 E1：海軍擴充 =====
NAVAL = [
    # --- 老式護衛艦 053 系列 ---
    mk("type-053h2g","053H2G型護衛艦（江衛I級）","Type 053H2G Jiangwei I","Type 053H2G","warship","海軍",
       aliases=["江衛I","Jiangwei I"],weight="滿載約 2,250 噸",length="112 m",crew="170",
       caliber="100mm 雙聯裝砲",cap="6×YJ-83 反艦、HQ-61 防空、2×3 魚雷",mob="護衛艦（FFG）",
       notes="江衛I級護衛艦，1990年代服役，反艦/防空/反潛。",tags=["護衛艦","江衛"],
       form_zh="飛彈護衛艦（江衛I級）",wiki="Type 053 frigate"),
    mk("type-053h1g","053H1G型護衛艦（江湖V級）","Type 053H1G Jianghu V","Type 053H1G","warship","海軍",
       aliases=["江湖V","Jianghu V"],weight="滿載約 1,900 噸",length="103 m",crew="200",
       caliber="2×100mm 砲",cap="8×YJ-83 反艦",mob="護衛艦（FF）",
       notes="江湖V級護衛艦，近岸巡邏/護漁執法常見。",tags=["護衛艦","江湖"],
       form_zh="飛彈護衛艦（江湖V級）",wiki="Type 053 frigate"),
    mk("type-053h","053H型護衛艦（江湖I級）","Type 053H Jianghu I","Type 053H","warship","海軍",
       aliases=["江湖I","Jianghu"],weight="滿載約 1,700 噸",length="103 m",crew="200",
       caliber="2×100mm 砲",cap="SY-1／YJ-8 反艦",mob="護衛艦（FF，多已除役/外援）",
       notes="江湖級護衛艦，早期主力，部分外援他國。",tags=["護衛艦","江湖"],
       form_zh="飛彈護衛艦（江湖I級）",wiki="Type 053 frigate"),
    # --- 獵潛艇 / 砲艇 ---
    mk("type-037","037型獵潛艇（海南級）","Type 037 Hainan-class","Type 037","patrol_boat","海軍",
       aliases=["海南級","Hainan"],weight="滿載約 430 噸",length="58.8 m",crew="70",
       caliber="4×57mm＋4×25mm",cap="反潛火箭深彈、深水炸彈",mob="近岸獵潛艇",
       notes="海南級獵潛艇，近岸反潛/巡邏，數量多。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-037is","037IS型獵潛艇（海青級）","Type 037IS Haiqing-class","Type 037IS","patrol_boat","海軍",
       aliases=["海青級","Haiqing"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm＋2×2 14.5mm",cap="反潛火箭深彈",mob="近岸獵潛艇",
       notes="海青級獵潛艇，037 改良反潛型。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-062","062型砲艇（上海級）","Type 062 Shanghai-class","Type 062","patrol_boat","海軍",
       aliases=["上海級","Shanghai"],weight="滿載約 135 噸",length="38.8 m",crew="36",
       caliber="2×2 37mm＋2×2 25mm",cap="近岸巡邏/砲擊",mob="近岸砲艇",
       notes="上海級砲艇，近岸巡邏，產量極大、大量外援。",tags=["砲艇","近岸"],
       form_zh="近岸巡邏砲艇（PGB）",wiki="Shanghai-class gunboat"),
    mk("type-021","021型飛彈快艇（黃蜂級）","Type 021 Huangfeng-class","Type 021","patrol_boat","海軍",
       aliases=["黃蜂級","Huangfeng","Osa"],weight="滿載約 205 噸",length="38.6 m",crew="30",
       caliber="2×2 30mm",cap="4×SY-1／YJ-8 反艦飛彈",mob="飛彈快艇（PTG）",
       notes="黃蜂級飛彈快艇（蘇聯 Osa 衍生），舊式，逐步由 022 取代。",tags=["飛彈快艇"],
       form_zh="飛彈快艇（PTG）",wiki="Type 021-class missile boat"),
    # --- 掃雷/獵雷 ---
    mk("type-081","081型獵掃雷艦（渦藏級）","Type 081 Wozang-class","Type 081","minesweeper","海軍",
       aliases=["渦藏級","Wozang"],weight="滿載約 575 噸",length="55 m",crew="—",
       caliber="1×2 25mm",cap="獵雷聲納、遙控獵雷具",mob="獵掃雷艦（MHC）",
       notes="渦藏級獵掃雷艦，玻璃鋼艦體、遙控獵雷。",tags=["掃雷","獵雷"],
       form_zh="獵掃雷艦（MHC）",wiki="Type 081 minesweeper"),
    mk("type-082","082型掃雷艦（渦掃級）","Type 082 Wosao-class","Type 082","minesweeper","海軍",
       aliases=["渦掃級","Wosao"],weight="滿載約 400 噸",length="44.8 m",crew="—",
       caliber="2×2 25mm",cap="機械/電磁/聲掃雷具",mob="掃雷艦（MSC）",
       notes="渦掃級掃雷艦，近岸掃雷。",tags=["掃雷"],
       form_zh="掃雷艦（MSC）",wiki="Type 082 minesweeper"),
    # --- 兩棲 ---
    mk("type-073","073型登陸艦（玉登級）","Type 073 Yudeng-class","Type 073","amphibious_ship","海軍",
       aliases=["玉登級","Yudeng"],weight="滿載約 1,850 噸",length="87 m",crew="—",
       caliber="機砲",cap="約 500 噸裝載/戰車、兵員",mob="中型登陸艦（LSM）",
       notes="玉登級中型登陸艦。",tags=["登陸艦","兩棲"],
       form_zh="中型登陸艦（LSM）",wiki="Type 073 landing ship"),
    mk("type-074","074型登陸艦（玉北級）","Type 074 Yubei-class","Type 074","amphibious_ship","海軍",
       aliases=["玉北級","Yubei"],weight="滿載約 800 噸",length="58.4 m",crew="—",
       caliber="機砲",cap="裝甲車/兵員登陸",mob="通用登陸艇（LCU）",
       notes="玉北級通用登陸艇。",tags=["登陸艇","兩棲"],
       form_zh="通用登陸艇（LCU）",wiki="Type 074 landing ship"),
    # --- 潛艇 ---
    mk("type-032","032型潛艇（清級）","Type 032 Qing-class","Type 032","submarine","海軍",cat="vehicle",
       aliases=["清級","Qing"],weight="水下約 6,628 噸",length="92.6 m",crew="88",
       caliber="魚雷/飛彈試射",cap="潛射彈道/巡航飛彈試驗平台（JL-2／JL-3 試射）",mob="常規動力試驗潛艇",
       notes="清級試驗潛艇，全球最大常規潛艇之一，用於潛射飛彈試驗。",tags=["潛艇","試驗"],
       form_zh="試驗潛艇（SSB test）",wiki="Type 032 submarine"),
    mk("type-039c","039C型潛艇（元級改）","Type 039C Yuan-class","Type 039C","submarine","海軍",cat="vehicle",
       aliases=["元級改","Yuan"],weight="水下約 3,600 噸",length="77.6 m",crew="—",
       caliber="533mm 魚雷",cap="YJ-18/YJ-82 潛射反艦、AIP 不依賴空氣推進",mob="常規動力攻擊潛艇（SSK/AIP）",
       notes="元級最新改型，具匿蹤外形與 AIP。",tags=["潛艇","AIP"],
       form_zh="常規攻擊潛艇（AIP）",wiki="Type 039A submarine"),
    mk("type-092","092型戰略核潛艇（夏級）","Type 092 Xia-class","Type 092","submarine","海軍",cat="vehicle",
       aliases=["夏級","Xia"],weight="水下約 8,000 噸",length="120 m",crew="140",
       caliber="彈道飛彈",cap="12×JL-1 潛射彈道飛彈",mob="彈道飛彈核潛艇（SSBN）",
       notes="夏級，中國第一代戰略核潛艇（1艘）。",tags=["核潛艇","SSBN"],
       form_zh="彈道飛彈核潛艇（SSBN）",wiki="Type 092 submarine"),
    mk("type-096","096型戰略核潛艇（唐級，研發中）","Type 096 Tang-class","Type 096","submarine","海軍",cat="vehicle",
       aliases=["唐級","Tang"],weight="—",length="—",crew="—",
       caliber="彈道飛彈",cap="JL-3 潛射洲際彈道飛彈（推測）",mob="次世代彈道飛彈核潛艇（SSBN，研發中）",
       notes="唐級次世代 SSBN，發展中，諸元為外界推測。",tags=["核潛艇","SSBN","研發中"],
       form_zh="次世代彈道飛彈核潛艇（SSBN）",wiki="Type 096 submarine"),
    mk("type-033","033型潛艇（羅密歐級）","Type 033 Romeo-class","Type 033","submarine","海軍",cat="vehicle",
       aliases=["羅密歐級","Romeo"],weight="水下約 1,712 噸",length="76.6 m",crew="54",
       caliber="533mm 魚雷",cap="魚雷/水雷（舊式，多除役/訓練）",mob="常規動力潛艇（舊式）",
       notes="羅密歐級（蘇聯衍生），舊式，多已退役或訓練用。",tags=["潛艇","舊式"],
       form_zh="常規潛艇（舊式）",wiki="Type 033 submarine"),
    # --- 補給/輔助/特種艦 ---
    mk("type-904","904型補給艦（大運級）","Type 904 Dayun-class","Type 904","replenishment","海軍",
       aliases=["大運級","Dayun"],weight="滿載約 15,000 噸",length="156 m",crew="—",
       caliber="機砲",cap="島礁補給、乾貨/物資運輸",mob="島礁補給艦（AKS）",
       notes="大運級島礁補給艦，南海島礁後勤。",tags=["補給艦","後勤"],
       form_zh="島礁補給艦（AKS）",wiki="Type 904 replenishment ship"),
    mk("type-905","905型補給艦（福清級）","Type 905 Fuqing-class","Type 905","replenishment","海軍",
       aliases=["福清級","Fuqing"],weight="滿載約 21,750 噸",length="168.2 m",crew="130",
       caliber="機砲",cap="燃油/彈藥/乾貨橫向補給",mob="遠洋綜合補給艦（AOR，舊式）",
       notes="福清級綜合補給艦，第一代遠洋補給艦。",tags=["補給艦","AOR"],
       form_zh="綜合補給艦（AOR）",wiki="Fuqing-class tanker"),
    mk("type-926","926型潛艇支援艦（大江級）","Type 926 Dajiang-class","Type 926","auxiliary","海軍",
       aliases=["大江級","Dajiang"],weight="滿載約 9,500 噸",length="156 m",crew="—",
       caliber="機砲",cap="搭載 LR-7 深潛救生艇、潛艇救援",mob="潛艇支援/救援艦（ASR）",
       notes="大江級潛艇支援艦，搭載深潛救生艇。",tags=["潛艇救援","支援艦"],
       form_zh="潛艇支援救援艦（ASR）",wiki="Type 926 submarine support ship"),
    mk("type-920","920型醫院船（和平方舟）","Type 920 Anwei-class (Peace Ark)","Type 920","hospital_ship","海軍",
       aliases=["和平方舟","Peace Ark","岱山島"],weight="滿載約 14,000 噸",length="178 m",crew="醫護 428",
       caliber="—",cap="300 床位、手術室、遠海醫療/人道救援",mob="醫院船（AH）",
       notes="和平方舟醫院船，遠海醫療與人道任務，多次出訪。",tags=["醫院船","人道"],
       form_zh="醫院船（AH）",wiki="Chinese hospital ship Peace Ark"),
    mk("yuanwang","遠望號測量船（航天測控）","Yuanwang tracking ship","Yuanwang","survey_ship","海軍",
       aliases=["遠望","Yuanwang"],weight="滿載約 25,000 噸",length="222 m",crew="—",
       caliber="—",cap="航天測控天線、飛彈/衛星彈道測量",mob="航天遠洋測量船",
       notes="遠望系列航天測量船，支援衛星/飛彈測控。",tags=["測量船","航天測控"],
       form_zh="航天遠洋測量船",wiki="Yuanwang"),
    mk("type-636a","636A型測量船","Type 636A survey ship","Type 636A","survey_ship","海軍",
       aliases=["636A"],weight="滿載約 5,900 噸",length="129.3 m",crew="—",
       caliber="—",cap="海洋/水文調查、聲納測繪",mob="海洋測量船（AGS）",
       notes="636A 海洋綜合調查測量船。",tags=["測量船","海洋調查"],
       form_zh="海洋測量船（AGS）",wiki="Type 636A survey ship"),
    # --- 海警（海上執法）---
    mk("type-818","818型海警船（昭頭級）","Type 818 Zhaotou-class CCG cutter","Type 818","coast_guard","海警",
       aliases=["昭頭級","Zhaotou","海警2901","海警3901"],weight="滿載約 12,000 噸",length="165 m",crew="—",
       caliber="76mm 主砲＋副砲",cap="世界最大海警執法船（基於 054A 技術）",mob="大型海警執法船",
       notes="昭頭級海警船，滿載萬噸，世界最大海上執法船。",tags=["海警","執法"],
       form_zh="大型海警巡防船（CG cutter）",wiki="Zhaotou-class patrol vessel"),
    mk("type-718b","718B型海警船","Type 718B CCG cutter","Type 718B","coast_guard","海警",
       aliases=["718B"],weight="滿載約 4,000 噸",length="—",crew="—",
       caliber="76mm 主砲",cap="遠海維權執法巡邏",mob="海警巡防船",
       notes="718B 型海警巡防船。",tags=["海警","執法"],
       form_zh="海警巡防船（CG cutter）",wiki="China Coast Guard"),
]

# ===== 批次 E2：空軍／陸航擴充（直升機、老式機、無人機、特種機）=====
AIR = [
    mk("z-8g","直-8G 通用運輸直升機","Z-8G transport helicopter","Z-8G","helicopter","陸軍",
       aliases=["直8G"],weight="最大起飛約 13,000 kg",crew="機組 3＋27 兵",rng="航程約 800 km",
       cap="運兵/物資、可吊掛",mob="中型運輸直升機",notes="直-8 系列通用運輸直升機。",
       tags=["直升機","運輸"],form_zh="中型運輸直升機",wiki="Harbin Z-8"),
    mk("z-8l","直-8L 大型運輸直升機","Z-8L heavy transport helicopter","Z-8L","helicopter","陸軍",
       aliases=["直8L"],weight="最大起飛約 15,000 kg",crew="機組＋大量兵員",rng="航程約 900 km",
       cap="加寬機身、可載輕型車輛",mob="大型運輸直升機",notes="直-8 加寬機身重型運輸型。",
       tags=["直升機","運輸"],form_zh="大型運輸直升機",wiki="Harbin Z-8"),
    mk("z-9w","直-9W 武裝直升機","Z-9W armed helicopter","Z-9W","helicopter_attack","陸軍",
       aliases=["直9W"],weight="最大起飛約 4,100 kg",crew="2",rng="航程約 1,000 km",
       cap="HJ-8 反戰車飛彈、火箭、機砲",mob="輕型武裝直升機",notes="直-9 武裝偵察/攻擊型（海豚衍生）。",
       tags=["直升機","武裝"],form_zh="輕型武裝直升機",wiki="Harbin Z-9"),
    mk("z-19e","直-19E 偵察攻擊直升機","Z-19E scout/attack helicopter","Z-19E","helicopter_attack","陸軍",
       aliases=["直19E"],weight="最大起飛約 4,500 kg",crew="2",rng="航程約 700 km",
       cap="天燕-90 空對空、反戰車飛彈、火箭",mob="偵察/攻擊直升機",notes="直-19 出口/改良型，串列雙座。",
       tags=["直升機","偵攻"],form_zh="偵察攻擊直升機",wiki="Harbin Z-19"),
    mk("z-11wb","直-11WB 武裝偵察直升機","Z-11WB armed scout","Z-11WB","helicopter_attack","陸軍",
       aliases=["直11WB"],weight="最大起飛約 2,200 kg",crew="2",rng="航程約 600 km",
       cap="輕型反戰車飛彈、機槍、火箭",mob="輕型武裝偵察直升機",notes="直-11 武裝偵察型。",
       tags=["直升機","武裝"],form_zh="輕型武裝偵察直升機",wiki="Changhe Z-11"),
    mk("mi-171","米-171 中型運輸直升機","Mil Mi-171","Mi-171","helicopter","陸軍",
       aliases=["Mi-171","米171"],weight="最大起飛約 13,000 kg",crew="機組 3＋24 兵",rng="航程約 590 km",
       cap="運兵/物資、可外掛武器",mob="中型運輸直升機（俄製）",notes="米-171 中型運輸直升機，陸航主力運輸機隊。",
       tags=["直升機","運輸","俄製"],form_zh="中型運輸直升機",wiki="Mil Mi-8"),
    mk("z-15","直-15 中型多用途直升機","Z-15 (AC352)","Z-15","helicopter","陸軍",
       aliases=["AC352","直15"],weight="最大起飛約 7,500 kg",crew="機組＋14 兵",rng="航程約 850 km",
       cap="運輸/搜救/多用途",mob="中型多用途直升機",notes="直-15／AC352 中型直升機（與空巴 H175 同源）。",
       tags=["直升機","多用途"],form_zh="中型多用途直升機",wiki="Airbus Helicopters H175"),
    # 老式作戰機
    mk("q-5","強-5 攻擊機","Nanchang Q-5","Q-5","aircraft_strike","空軍",
       aliases=["強5","A-5","Fantan"],weight="最大起飛約 12,000 kg",crew="1",rng="作戰半徑約 400 km",
       caliber="2×23mm 機砲",cap="炸彈/火箭/近距空對空，載彈約 2,000 kg",mob="Mach 1.12；2×渦噴-6",
       notes="強-5 對地攻擊機（MiG-19 衍生），已大量退役。",tags=["攻擊機","舊式"],
       form_zh="對地攻擊機",wiki="Nanchang Q-5"),
    mk("j-7e","殲-7E／G 戰鬥機","Chengdu J-7E/G","J-7E","aircraft_fighter","空軍",
       aliases=["殲7E","殲7G","J-7G"],weight="最大起飛約 9,100 kg",crew="1",rng="作戰半徑約 600 km",
       caliber="2×30mm",cap="PL-5／PL-8 近距空對空、火箭/炸彈",mob="Mach 2；渦噴-13（雙三角翼改良）",
       notes="殲-7 後期改良型（雙三角翼、改良航電），逐步退役。",tags=["戰鬥機","舊式"],
       form_zh="輕型戰鬥機（殲-7 後期型）",wiki="Chengdu J-7"),
    mk("j-8b","殲-8B 攔截機","Shenyang J-8B","J-8B","aircraft_fighter","空軍",
       aliases=["殲8B"],weight="最大起飛約 17,800 kg",crew="1",rng="作戰半徑約 800 km",
       caliber="23mm 機砲",cap="PL-5／PL-8／PL-11、火箭",mob="Mach 2.2；2×渦噴-13",
       notes="殲-8B 全天候攔截機，逐步退役/改偵察電戰。",tags=["攔截機","舊式"],
       form_zh="攔截戰鬥機（殲-8B）",wiki="Shenyang J-8"),
    # 無人機
    mk("ch-3","彩虹-3 察打無人機","CASC CH-3","CH-3","uav","空軍",
       aliases=["彩虹3","CH-3"],weight="最大起飛約 640 kg",crew="無人",rng="航程約 2,400 km／滯空 12h",
       cap="AR-1 反戰車飛彈、FT 系列導引炸彈",mob="中空長航時；螺旋槳",
       notes="彩虹-3 察打一體無人機，外銷多國。",tags=["無人機","察打"],
       form_zh="察打一體無人機（彩虹-3）",wiki="CASC Rainbow"),
    mk("wing-loong-10","翼龍-10 高空長航時無人機","Wing Loong-10 (Cloud Shadow)","WL-10","uav","空軍",
       aliases=["雲影","Cloud Shadow","WZ-10 UAV"],weight="最大起飛約 3,200 kg",crew="無人",
       rng="航程約 4,000 km／升限 14,000 m",cap="偵察/電子情報/精確打擊",mob="噴射動力、高空高速",
       notes="翼龍-10（雲影）噴射高空無人機。",tags=["無人機","高空"],
       form_zh="高空長航時無人機（翼龍-10）",wiki="Wing Loong 10"),
    mk("wz-5","無偵-5 高空偵察無人機（舊式）","WZ-5 recon drone","WZ-5","uav","空軍",
       aliases=["無偵5","Chang Hong"],weight="—",crew="無人",rng="—",
       cap="高空照相偵察（舊式）",mob="早期噴射偵察無人機",notes="無偵-5 早期高空偵察無人機（長虹），歷史型。",
       tags=["無人機","偵察","舊式"],form_zh="高空偵察無人機（舊式）",wiki="Chengdu WZ-5"),
    mk("asn-206","ASN-206 戰術無人機","ASN-206 tactical UAV","ASN-206","uav","陸軍",
       aliases=["ASN-206"],weight="最大起飛約 222 kg",crew="無人",rng="航程約 150 km／滯空 8h",
       cap="戰場偵察/砲兵校射/電子偵察",mob="活塞螺旋槳、彈射起飛",notes="ASN-206 戰術偵察無人機（西工大）。",
       tags=["無人機","戰術偵察"],form_zh="戰術偵察無人機（ASN-206）",wiki="ASN-206"),
    # 特種任務機
    mk("y-8g","運-8G 電子戰機","Y-8G ECM aircraft","Y-8G","aircraft_recon","空軍",
       aliases=["運8G","GX-4"],weight="—",crew="—",rng="—",cap="電子干擾/壓制（高新4號）",
       mob="Y-8 平台特種機",notes="運-8G 電子戰/干擾機（高新工程）。",tags=["電子戰","特種機"],
       form_zh="電子戰機（Y-8 平台）",wiki="Shaanxi Y-8"),
    mk("y-9g","運-9G 電子戰機","Y-9G ECM aircraft","Y-9G","aircraft_recon","空軍",
       aliases=["運9G","高新12"],weight="—",crew="—",rng="航程約 5,000 km",cap="電子偵察/干擾",
       mob="Y-9 平台特種機",notes="運-9G 電子戰機（高新工程）。",tags=["電子戰","特種機"],
       form_zh="電子戰機（Y-9 平台）",wiki="Shaanxi Y-9"),
    mk("kj-500a","空警-500A 預警機","KJ-500A AEW&C","KJ-500A","aircraft_aew","空軍",
       aliases=["空警500A"],weight="MTOW 約 77 噸",crew="多名操作員",rng="滯空約 12h",
       cap="三面 AESA（360°）＋空中受油",mob="Y-9 平台預警機",notes="空警-500A，加裝空中受油探管的改良型。",
       tags=["預警機","AEW"],form_zh="空中預警管制機（KJ-500A）",wiki="KJ-500"),
]

# ===== 批次 E3：陸軍擴充（老式坦克、輪式裝甲、火砲、工兵/搶救/架橋）=====
GROUND = [
    mk("type-59","59式中型坦克","Type 59 MBT","Type 59","mbt","陸軍",
       aliases=["59式","WZ120"],weight="約 36 噸",crew="4",caliber="100mm 線膛砲",
       rng="公路 50 km/h",mob="12150L V12 520hp",armor="鑄造均質裝甲",
       cap="蘇聯 T-54A 衍生，中國第一代主戰坦克",notes="59式中型坦克，產量極大，衍生眾多，部分仍後備/訓練。",
       tags=["坦克","舊式"],form_zh="中型坦克（T-54A 衍生）",wiki="Type 59 tank"),
    mk("type-59d","59D式主戰坦克","Type 59D MBT","Type 59D","mbt","陸軍",
       aliases=["59D式"],weight="約 39 噸",crew="4",caliber="105mm 線膛砲（可射砲射飛彈）",
       rng="公路 50 km/h",mob="580hp 柴油",armor="複合＋爆炸反應裝甲",
       cap="105mm 砲、火控升級、砲射飛彈",notes="59式深度現代化型，換 105mm 砲與 ERA。",
       tags=["坦克"],form_zh="主戰坦克（59 現代化）",wiki="Type 59 tank"),
    mk("type-69","69式主戰坦克","Type 69 MBT","Type 69","mbt","陸軍",
       aliases=["69式","WZ121"],weight="約 36.5 噸",crew="4",caliber="100mm 滑膛砲",
       rng="公路 50 km/h",mob="12150L-7 580hp",armor="鑄造裝甲",
       cap="59 式改良，大量外銷（兩伊戰爭）",notes="69式主戰坦克，外銷量大，國內多退役。",
       tags=["坦克","舊式"],form_zh="主戰坦克（69 式）",wiki="Type 69 tank"),
    mk("type-79","79式主戰坦克","Type 79 MBT","Type 79","mbt","陸軍",
       aliases=["79式"],weight="約 37.5 噸",crew="4",caliber="105mm 線膛砲",
       rng="公路 50 km/h",mob="580hp 柴油",armor="鑄造＋複合",
       cap="首用 105mm 線膛砲與火控",notes="79式主戰坦克，69 改良、引進西方 105mm 砲技術。",
       tags=["坦克","舊式"],form_zh="主戰坦克（79 式）",wiki="Type 79 tank"),
    mk("type-80","80式主戰坦克","Type 80 MBT","Type 80","mbt","陸軍",
       aliases=["80式","ZTZ-80"],weight="約 38 噸",crew="4",caliber="105mm 線膛砲",
       rng="公路 60 km/h",mob="730hp 柴油",armor="複合裝甲",
       cap="新底盤（六對負重輪）、現代火控",notes="80式主戰坦克，第二代國產坦克起點，衍生 88/96 式。",
       tags=["坦克"],form_zh="主戰坦克（80 式）",wiki="Type 80 tank"),
    mk("ptl-02","PTL-02 輪式突擊砲","PTL-02 assault gun","PTL-02","assault_gun","陸軍",
       aliases=["PTL02","100mm 輪突"],weight="約 19 噸",crew="4",caliber="100mm 線膛砲",
       rng="公路 85 km/h",mob="6×6 輪式",armor="防輕武器/破片",
       cap="100mm 砲、反裝甲/火力支援",notes="PTL-02 輪式突擊砲（WMZ551 底盤），快速反應部隊。",
       tags=["突擊砲","輪式"],form_zh="輪式突擊砲（100mm）",wiki="PTL02"),
    mk("wz-523","WZ-523 輪式裝甲運兵車","WZ-523 APC","WZ-523","apc_wheeled","陸軍",
       aliases=["WZ523"],weight="約 11.5 噸",crew="2＋10 兵",caliber="12.7mm 機槍",
       rng="公路 80 km/h",mob="6×6 兩棲",armor="鋼裝甲防輕武器",
       cap="運兵/維穩/兩棲",notes="WZ-523 輪式裝甲運兵車，亦供武警維穩。",
       tags=["裝甲車","輪式"],form_zh="輪式裝甲運兵車（APC）",wiki="WZ523"),
    mk("plz-45","PLZ-45 155mm 自走榴彈砲","PLZ-45 SPH","PLZ-45","sph","陸軍",
       aliases=["PLZ45"],weight="約 33 噸",crew="5",caliber="155mm/45 倍徑",
       rng="射程 39 km（底排增程）",mob="履帶自走",armor="鋼裝甲",
       cap="外銷主力（科威特、沙烏地等）",notes="PLZ-45 外銷型 155mm 自走砲，成套彈藥/指揮系統。",
       tags=["自走砲","外銷"],form_zh="自走榴彈砲（155mm，外銷）",wiki="PLZ-45"),
    mk("plz-52","PLZ-52 155mm 自走榴彈砲","PLZ-52 SPH","PLZ-52","sph","陸軍",
       aliases=["PLZ52"],weight="約 43 噸",crew="5",caliber="155mm/52 倍徑",
       rng="射程 53 km（火箭增程）",mob="履帶自走",armor="鋼裝甲",
       cap="PLZ-05 外銷升級版",notes="PLZ-52 為 PLZ-05 的 52 倍徑外銷升級型，射程更遠。",
       tags=["自走砲","外銷"],form_zh="自走榴彈砲（155mm/52）",wiki="PLZ-52"),
    mk("sh-15","SH-15 155mm 車載榴彈砲","SH-15 truck howitzer","SH-15","truck_howitzer","陸軍",
       aliases=["SH15","PCL-181 外銷"],weight="約 22 噸",crew="6",caliber="155mm/52 倍徑",
       rng="射程 20 km（一般）/53 km（增程）",mob="6×6 卡車底盤",armor="裝甲駕駛室",
       cap="PCL-181 的外銷型（巴基斯坦等）",notes="SH-15 車載榴彈砲，PCL-181 外銷版本。",
       tags=["車載砲","外銷"],form_zh="車載榴彈砲（155mm）",wiki="SH-15"),
    mk("phl-11","PHL-11 122mm 火箭砲","PHL-11 MLRS","PHL-11","mlrs","陸軍",
       aliases=["PHL11","Type 11"],weight="約 22 噸",crew="—",caliber="122mm×40 管",
       rng="射程 20–40 km",mob="6×6 車載、模組化裝填",armor="裝甲駕駛室",
       cap="40 聯裝 122mm、模組快速再裝填",notes="PHL-11 模組化 122mm 火箭砲。",
       tags=["火箭砲","122mm"],form_zh="122mm 多管火箭砲",wiki="PHL-11"),
    mk("gsl-131","GSL-131 掃雷破障車","GSL-131 mine-clearing vehicle","GSL-131","engineer","陸軍",
       aliases=["GSL131"],weight="約 30 噸",crew="2",caliber="—",
       rng="—",mob="履帶（99/96 底盤）",armor="裝甲",
       cap="掃雷犁/爆破掃雷索、開闢通路",notes="GSL-131 裝甲掃雷破障車，為裝甲部隊開路。",
       tags=["工兵","掃雷"],form_zh="裝甲掃雷破障車",wiki="GSL-131"),
    mk("gcz-112","GCZ-112 裝甲工程車","GCZ-112 combat engineer vehicle","GCZ-112","engineer","陸軍",
       aliases=["GCZ112"],weight="約 38 噸",crew="3",caliber="12.7mm 機槍",
       rng="—",mob="履帶裝甲底盤",armor="裝甲",
       cap="推土鏟/挖掘臂/絞盤，構工/清障",notes="GCZ-112 裝甲工程車，戰場構工與清障。",
       tags=["工兵","構工"],form_zh="裝甲工程車（CEV）",wiki="GCZ-112"),
    mk("type-84-bridge","84式架橋坦克","Type 84 bridgelayer","Type 84","bridge","陸軍",
       aliases=["84式架橋","HJJ-84"],weight="約 38 噸",crew="3",caliber="—",
       rng="—",mob="69/79 坦克底盤",armor="裝甲",
       cap="剪刀式車轍橋、跨距約 18 m",notes="84式架橋坦克，快速架設車轍橋供裝甲通過。",
       tags=["工兵","架橋"],form_zh="架橋坦克（AVLB）",wiki="Type 84 bridgelayer"),
    mk("type-654-arv","654式裝甲搶救車","Type 654 ARV","Type 654","recovery","陸軍",
       aliases=["654式","搶救車"],weight="約 38 噸",crew="4",caliber="12.7mm 機槍",
       rng="—",mob="履帶裝甲底盤",armor="裝甲",
       cap="絞盤/吊臂/推土鏟，戰場搶修拖救",notes="654 式裝甲搶救車，拖救與野戰搶修受損戰車。",
       tags=["工兵","搶救"],form_zh="裝甲搶救車（ARV）",wiki="Type 654 armoured recovery vehicle"),
]

def merge(batch):
    data = json.loads(OUT.read_text(encoding="utf-8")) if OUT.exists() else []
    by = {x["id"]: x for x in data}
    for it in batch:
        by[it["id"]] = it
    out = list(by.values())
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(out), len(batch)

if __name__ == "__main__":
    n = 0
    for name, batch in [("E1 海軍", NAVAL), ("E2 空軍/陸航", AIR), ("E3 陸軍", GROUND)]:
        total, cnt = merge(batch)
        print(f"批次 {name}：{cnt} 筆")
        n = total
    print(f"new_items_extra.json 現有 {n} 筆")
