#!/usr/bin/env python3
"""Grok 交叉比對後補漏的批次；沿用 expand_batches 的 mk/merge，累加到 new_items_extra.json。"""
from expand_batches import mk, W, merge

# ===== GX1：海軍缺漏（Grok naval_1 diff）=====
GX1 = [
    # 早期/變體驅逐艦
    mk("type-052","052型驅逐艦（旅滬級）","Type 052 Luhu-class","Type 052","warship","海軍",
       aliases=["旅滬級","Luhu","哈爾濱","青島"],weight="滿載約 4,800 噸",length="144 m",crew="260",
       caliber="100mm 砲",cap="8×YJ-83 反艦、HQ-7 防空、2 架直升機",mob="驅逐艦（DDG）",branch_hint="海軍",
       notes="旅滬級驅逐艦（哈爾濱/青島），首用燃氣渦輪與西方技術的過渡型。",tags=["驅逐艦"],
       form_zh="飛彈驅逐艦（旅滬級）",wiki="Type 052 destroyer"),
    mk("type-051dt","051DT型驅逐艦（旅大III級）","Type 051DT Luda III","Type 051DT","warship","海軍",
       aliases=["旅大III","Luda III"],weight="滿載約 3,730 噸",length="132 m",crew="280",
       caliber="2×2 130mm 砲",cap="YJ-8 反艦、防空改良",mob="驅逐艦（DDG，已退役）",branch_hint="海軍",
       notes="旅大級後期改良型（防空/電子升級），已退役。",tags=["驅逐艦","舊式"],
       form_zh="飛彈驅逐艦（旅大III）",wiki="Type 051 destroyer"),
    mk("type-051g","051G型驅逐艦（旅大IV級）","Type 051G Luda IV","Type 051G","warship","海軍",
       aliases=["旅大IV","Luda IV","湛江"],weight="滿載約 3,730 噸",length="132 m",crew="280",
       caliber="2×2 130mm 砲",cap="YJ-8 反艦、武器/雷達更新",mob="驅逐艦（DDG，已退役）",branch_hint="海軍",
       notes="旅大級末期升級型，已退役。",tags=["驅逐艦","舊式"],
       form_zh="飛彈驅逐艦（旅大IV）",wiki="Type 051 destroyer"),
    mk("type-055a","055A型驅逐艦（改進型，研發中）","Type 055A (reported)","Type 055A","warship","海軍",
       aliases=["055A","Renhai improved"],weight="—",length="—",crew="—",
       caliber="130mm 砲",cap="112 垂發、改進推進/感測（外界討論）",mob="大型驅逐艦（後續批次）",branch_hint="海軍",
       notes="055 改進/後續批次，公開討論中，諸元推測。",tags=["驅逐艦","研發中"],
       form_zh="大型飛彈驅逐艦（055 改進）",wiki="Type 055 destroyer"),
    mk("sovremenny-em","現代級驅逐艦（956EM）","Sovremenny 956EM","Project 956EM","warship","海軍",
       aliases=["956EM","泰州","寧波"],weight="滿載約 7,940 噸",length="156 m",crew="296",
       caliber="2×2 130mm 砲",cap="8×3M-80MBE 日炙超音速反艦、施基利防空",mob="驅逐艦（俄製改進）",branch_hint="海軍",
       notes="現代級改進型（泰州/寧波），強化反艦與防空。",tags=["驅逐艦","俄製"],
       form_zh="飛彈驅逐艦（956EM）",wiki="Sovremenny-class destroyer"),
    # 早期護衛艦
    mk("type-065","065型護衛艦（江南級）","Type 065 Jiangnan-class","Type 065","warship","海軍",
       aliases=["江南級","Jiangnan"],weight="滿載約 1,600 噸",length="90 m",crew="175",
       caliber="3×100mm 砲",cap="火砲護衛艦（無反艦飛彈）",mob="護衛艦（FF，已退役）",branch_hint="海軍",
       notes="江南級護衛艦，早期國產火砲護衛艦，已退役。",tags=["護衛艦","舊式"],
       form_zh="火砲護衛艦（江南級）",wiki="Type 065 frigate"),
    mk("type-053k","053K型護衛艦（江東級）","Type 053K Jiangdong-class","Type 053K","warship","海軍",
       aliases=["江東級","Jiangdong"],weight="滿載約 1,900 噸",length="103 m",crew="—",
       caliber="2×2 100mm 砲",cap="HQ-61 艦空飛彈試驗（首型防空護衛艦）",mob="護衛艦（FFG，已退役）",branch_hint="海軍",
       notes="江東級防空護衛艦，HQ-61 艦空飛彈試驗艦，已退役。",tags=["護衛艦","防空","舊式"],
       form_zh="防空護衛艦（江東級）",wiki="Type 053K frigate"),
    # 巡邏/近岸
    mk("type-037i","037I型獵潛艇（海青級基型）","Type 037I Haiqing-class","Type 037I","patrol_boat","海軍",
       aliases=["海青級","Haiqing"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm＋2×2 14.5mm",cap="反潛火箭深彈、近岸反潛巡邏",mob="近岸獵潛艇",branch_hint="海軍",
       notes="海青級獵潛艇基型（037 反潛改良）。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-037ig","037IG型飛彈艇（紅星級）","Type 037IG Houxin-class","Type 037IG","patrol_boat","海軍",
       aliases=["紅星級","Houxin"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm",cap="4×YJ-8 反艦飛彈（037 平台加裝反艦）",mob="近岸飛彈艇",branch_hint="海軍",
       notes="紅星級飛彈艇，037 加裝反艦飛彈的近岸型。",tags=["飛彈艇","近岸"],
       form_zh="近岸飛彈艇（PGG）",wiki="Houxin-class missile boat"),
    mk("type-026","026型魚雷艇（滬川級）","Type 026 Huchuan-class","Type 026","patrol_boat","海軍",
       aliases=["滬川級","Huchuan"],weight="滿載約 45 噸",length="21.8 m",crew="23",
       caliber="2×2 14.5mm",cap="2×533mm 魚雷、水翼高速",mob="水翼魚雷艇（舊式）",branch_hint="海軍",
       notes="滬川級水翼魚雷艇，冷戰近海打擊，已退役。",tags=["魚雷艇","水翼","舊式"],
       form_zh="水翼魚雷艇（舊式）",wiki="Huchuan-class torpedo boat"),
    mk("type-062i","062I型護衛艇（上海III級）","Type 062I Shanghai III","Type 062I","patrol_boat","海軍",
       aliases=["上海III","Shanghai II/III"],weight="滿載約 170 噸",length="41 m",crew="43",
       caliber="2×2 37mm＋2×2 25mm",cap="近岸巡邏/護衛（062 改進）",mob="近岸砲艇",branch_hint="海軍",
       notes="上海級改進型近岸巡邏砲艇。",tags=["砲艇","近岸","舊式"],
       form_zh="近岸巡邏砲艇（改進）",wiki="Shanghai-class gunboat"),
    # 艦載反艦飛彈
    mk("yj-8","鷹擊-8 反艦飛彈（C-801）","YJ-8 / C-801","YJ-8","asm","海軍",cat="weapon",
       aliases=["YJ-8","C-801","鷹擊8"],rng="約 42 km",caliber="反艦飛彈",cap="固體火箭、掠海亞音速、165kg 戰鬥部",
       mob="Mach 0.9；艦/岸射",branch_hint="海軍",notes="鷹擊-8 第一代國產掠海反艦飛彈（Exocet 級）。",
       tags=["反艦","亞音速"],form_zh="反艦飛彈（YJ-8）",wiki="YJ-8"),
    mk("yj-82","鷹擊-82 潛射反艦飛彈","YJ-82 sub-launched","YJ-82","asm","海軍",cat="weapon",
       aliases=["YJ-82","鷹擊82"],rng="約 40 km",caliber="潛射反艦飛彈",cap="潛艇魚雷管發射、掠海亞音速",
       mob="Mach 0.9；潛射",branch_hint="海軍",notes="鷹擊-8 的潛射型（潛艇發射反艦飛彈）。",
       tags=["反艦","潛射"],form_zh="潛射反艦飛彈（YJ-82）",wiki="YJ-8"),
    mk("yj-83k","鷹擊-83K 空射反艦飛彈","YJ-83K air-launched","YJ-83K","asm","海軍",cat="weapon",
       aliases=["YJ-83K","鷹擊83K"],rng="約 200 km（空射增程）",caliber="空射反艦飛彈",cap="渦噴、末端 Mach 1.4；海航 JH-7/H-6 掛載",
       mob="亞音速掠海；空射",branch_hint="海軍",notes="鷹擊-83 空射型，海軍航空兵對海打擊主力。",
       tags=["反艦","空射"],form_zh="空射反艦飛彈（YJ-83K）",wiki="YJ-83"),
    mk("yj-18b","鷹擊-18B 潛射反艦飛彈","YJ-18B sub-launched","YJ-18B","asm","海軍",cat="weapon",
       aliases=["YJ-18B","鷹擊18B"],rng="約 540 km",caliber="潛射反艦巡航飛彈",cap="潛艇發射、末端超音速衝刺",
       mob="次音速+超音速末端；潛射",branch_hint="海軍",notes="鷹擊-18 潛射型，元/商級潛艇裝備。",
       tags=["反艦","潛射"],form_zh="潛射反艦巡航飛彈（YJ-18B）",wiki="YJ-18"),
    mk("c-705","C-705 反艦飛彈","C-705","C-705","asm","海軍",cat="weapon",
       aliases=["C-705"],rng="約 75–140 km",caliber="輕型反艦飛彈",cap="快艇/直升機/岸射，雷達/電視導引",
       mob="亞音速掠海",branch_hint="海軍",notes="C-705 輕型反艦飛彈（外銷），小型載台適用。",
       tags=["反艦","外銷"],form_zh="輕型反艦飛彈（C-705）",wiki="C-705"),
    mk("c-704","C-704 反艦飛彈","C-704","C-704","asm","海軍",cat="weapon",
       aliases=["C-704"],rng="約 35 km",caliber="輕型反艦飛彈",cap="快艇用、電視/雷達導引",
       mob="亞音速掠海",branch_hint="海軍",notes="C-704 輕型反艦飛彈（外銷）。",
       tags=["反艦","外銷"],form_zh="輕型反艦飛彈（C-704）",wiki="C-704"),
    # 艦空飛彈
    mk("hhq-7","海紅旗-7 艦空飛彈","HHQ-7 / FM-90N","HHQ-7","sam","海軍",cat="weapon",
       aliases=["HHQ-7","海紅旗7","FM-90N"],rng="約 8–15 km",caliber="近程艦空飛彈",cap="點防空，053H3/054 等裝備",
       mob="指令/紅外導引",branch_hint="海軍",notes="海紅旗-7 艦載近程防空飛彈（紅旗-7 艦載型）。",
       tags=["艦空飛彈","近程"],form_zh="艦載近程防空飛彈（HHQ-7）",wiki="HQ-7"),
    mk("hhq-10","海紅旗-10 近防飛彈（FL-3000N）","HHQ-10 / FL-3000N","HHQ-10","sam","海軍",cat="weapon",
       aliases=["HHQ-10","海紅旗10","FL-3000N"],rng="約 9 km",caliber="末端近防飛彈",cap="18/24 聯裝、被動雷達+紅外，攔截反艦飛彈",
       mob="發射後鎖定",branch_hint="海軍",notes="海紅旗-10 艦載末端近防飛彈，攔截來襲反艦飛彈。",
       tags=["艦空飛彈","近防"],form_zh="艦載末端近防飛彈（HHQ-10）",wiki="HQ-10"),
    mk("hhq-16bc","海紅旗-16B/C 艦空飛彈","HHQ-16B/C","HHQ-16B","sam","海軍",cat="weapon",
       aliases=["HHQ-16B","HHQ-16C","海紅旗16改"],rng="約 70 km（增程）",caliber="中程艦空飛彈",cap="增程/改進導引，054A/052D 垂發",
       mob="半主動/主動雷達",branch_hint="海軍",notes="海紅旗-16 增程改進型，區域防空射程提升。",
       tags=["艦空飛彈","中程"],form_zh="艦載中程防空飛彈（HHQ-16 改）",wiki="HQ-16"),
    mk("hhq-9b","海紅旗-9B 艦空飛彈","HHQ-9B","HHQ-9B","sam","海軍",cat="weapon",
       aliases=["HHQ-9B","海紅旗9B"],rng="約 200+ km",caliber="遠程艦空飛彈",cap="增程/反彈道改進，052D/055 裝備",
       mob="慣性+主動雷達末端",branch_hint="海軍",notes="海紅旗-9 艦載增程型，遠程區域防空/反彈道。",
       tags=["艦空飛彈","遠程"],form_zh="艦載遠程防空飛彈（HHQ-9B）",wiki="HQ-9"),
    mk("rif-m","裡夫-M 艦空飛彈系統","Rif-M / S-300FM","Rif-M","sam","海軍",cat="weapon",
       aliases=["Rif-M","S-300FM","SA-N-20","裡夫"],rng="約 150 km",caliber="遠程艦空飛彈（俄製）",cap="051C 裝備、48N6 導彈、遠程區域防空",
       mob="半主動雷達",branch_hint="海軍",notes="俄製裡夫-M（S-300F 海軍型），裝備 051C 驅逐艦。",
       tags=["艦空飛彈","俄製"],form_zh="艦載遠程防空飛彈（Rif-M）",wiki="S-300 missile system"),
    mk("shtil","施基利 艦空飛彈系統","Shtil / 9M38","Shtil","sam","海軍",cat="weapon",
       aliases=["Shtil","9M38","SA-N-12","施基利"],rng="約 30–50 km",caliber="中程艦空飛彈（俄製）",cap="052B 裝備、單臂發射、中程防空",
       mob="半主動雷達",branch_hint="海軍",notes="俄製施基利中程艦空飛彈，裝備 052B 驅逐艦。",
       tags=["艦空飛彈","俄製"],form_zh="艦載中程防空飛彈（施基利）",wiki="9K37 Buk"),
    # 魚雷
    mk("yu-8","魚-8 火箭助飛魚雷","Yu-8 ASROC-type","Yu-8","torpedo","海軍",
       aliases=["Yu-8","魚8","CY-5"],rng="射程約 30–50 km",caliber="反潛飛彈/助飛魚雷",cap="垂發、火箭助推＋輕型魚雷，遠程反潛",
       mob="火箭助飛",branch_hint="海軍",notes="魚-8 火箭助飛魚雷（類 ASROC），055/052D 垂發反潛。",
       tags=["反潛","助飛魚雷"],form_zh="火箭助飛反潛魚雷（ASROC 型）",wiki="CY-5"),
    mk("yu-9","魚-9 魚雷","Yu-9 torpedo","Yu-9","torpedo","海軍",
       aliases=["Yu-9","魚9"],rng="—",caliber="通用魚雷",cap="新型輕/通用魚雷（公開型號）",
       mob="聲導",branch_hint="海軍",notes="魚-9 新型魚雷（公開資料有限）。",
       tags=["魚雷"],form_zh="通用魚雷",wiki="Chinese torpedo"),
    # 艦炮
    mk("hpj-38","H/PJ-38 型 130mm 艦炮","H/PJ-38 130mm naval gun","H/PJ-38","naval_gun","海軍",cat="weapon",
       aliases=["H/PJ-38","130mm 艦砲"],caliber="130mm/70 單管",rng="射程約 30 km（增程彈更遠）",
       cap="對海/對空/對岸、可射制導砲彈；052D/055 主砲",mob="全自動艦砲",branch_hint="海軍",
       notes="H/PJ-38 單管 130mm 艦砲，052D/055 主砲。",tags=["艦炮","130mm"],
       form_zh="130mm 艦炮（主砲）",wiki="H/PJ-38"),
    mk("hpj-26","H/PJ-26 型 76mm 艦炮","H/PJ-26 76mm naval gun","H/PJ-26","naval_gun","海軍",cat="weapon",
       aliases=["H/PJ-26","76mm 艦砲","AK-176 衍生"],caliber="76mm 單管",rng="射程約 16 km",
       cap="高射速對海/對空；054A/056 等主砲",mob="全自動艦砲",branch_hint="海軍",
       notes="H/PJ-26 76mm 艦砲（俄 AK-176 衍生），054A/056 主砲。",tags=["艦炮","76mm"],
       form_zh="76mm 艦炮",wiki="H/PJ-26"),
    # 艦載雷達
    mk("type-346","346型有源相控陣雷達（龍眼）","Type 346 Dragon Eye AESA","Type 346","naval_radar","海軍",cat="equipment",
       aliases=["346型","Dragon Eye","海之星"],cap="四面固定相控陣、對空/對海/火控，052C 裝備",
       sensors="S 波段有源相控陣（AESA）",mob="艦載固定四面陣",branch_hint="海軍",
       notes="346 型「海之星」相控陣雷達（龍眼），中華神盾核心，052C 裝備。",tags=["艦載雷達","相控陣"],
       form_zh="艦載有源相控陣雷達（346）",wiki="Type 346 radar"),
    mk("type-346a","346A型相控陣雷達","Type 346A AESA","Type 346A","naval_radar","海軍",cat="equipment",
       aliases=["346A型"],cap="052D 改進相控陣，探測距離/多目標能力提升",
       sensors="改進型有源相控陣",mob="艦載四面陣",branch_hint="海軍",
       notes="346A 相控陣雷達，052D 裝備，較 346 改進。",tags=["艦載雷達","相控陣"],
       form_zh="艦載相控陣雷達（346A）",wiki="Type 346 radar"),
    mk("type-346b","346B型大型相控陣雷達","Type 346B AESA","Type 346B","naval_radar","海軍",cat="equipment",
       aliases=["346B型"],cap="055 大型四面陣，雙波段配合，遠程對空/反彈道",
       sensors="大型有源相控陣",mob="艦載大型四面陣",branch_hint="海軍",
       notes="346B 大型相控陣雷達，055 驅逐艦裝備。",tags=["艦載雷達","相控陣"],
       form_zh="艦載大型相控陣雷達（346B）",wiki="Type 346 radar"),
    mk("type-382","382型三坐標對空雷達","Type 382 3D radar","Type 382","naval_radar","海軍",cat="equipment",
       aliases=["382型","Sea Eagle"],cap="054A 等三坐標對空搜索雷達",
       sensors="三坐標對空搜索雷達",mob="艦載旋轉天線",branch_hint="海軍",
       notes="382 型三坐標對空搜索雷達（俄 Fregat 衍生），054A 裝備。",tags=["艦載雷達","三坐標"],
       form_zh="艦載三坐標對空雷達（382）",wiki="Type 382 radar"),
]

# ===== GX2：海軍缺漏（Grok naval_2 diff）=====
def s(id, zh, en, desig, sub, *, aliases=None, weight="—", length="—", crew="—",
      cap="—", mob="—", notes="", tags=None, form="", wiki="", cat="vehicle", caliber="—"):
    return mk(id, zh, en, desig, sub, "海軍", cat=cat, aliases=aliases, weight=weight,
              length=length, crew=crew, caliber=caliber, cap=cap, mob=mob, notes=notes,
              tags=tags or [], form_zh=form, wiki=wiki, branch_hint="海軍")

GX2 = [
    # 潛艇變體
    s("type-093a","093A型攻擊核潛艇（商級改）","Type 093A Shang II","Type 093A","submarine",
      aliases=["商級改","Shang II"],weight="水下約 7,000 噸",length="約 110 m",crew="100",
      caliber="533mm 魚雷／垂發",cap="魚雷、YJ-18；傳增設垂直發射艙",mob="攻擊型核潛艇（SSN）",
      notes="093 改進型，降噪與武器升級，傳加裝垂發。",tags=["核潛艇","SSN"],form="攻擊型核潛艇（093A）",wiki="Type 093 submarine"),
    s("type-094a","094A型彈道導彈核潛艇（晉級改）","Type 094A Jin improved","Type 094A","submarine",
      aliases=["晉級改","Jin A"],weight="水下約 11,000 噸",length="約 135 m",crew="140",
      caliber="潛射彈道飛彈",cap="12×JL-2／JL-3 潛射彈道飛彈",mob="彈道導彈核潛艇（SSBN）",
      notes="094 改進型，圍殼與降噪改良，戰略核威懾主力。",tags=["核潛艇","SSBN"],form="彈道導彈核潛艇（094A）",wiki="Type 094 submarine"),
    s("type-033g","033G型導彈潛艇（武漢級）","Type 033G Wuhan-class SSG","Type 033G","submarine",
      aliases=["武漢級","Romeo mod"],weight="水下約 1,830 噸",length="76.6 m",crew="54",
      caliber="533mm 魚雷＋反艦飛彈",cap="033 改裝反艦飛彈試驗/作戰型",mob="常規潛艇（已退役）",
      notes="羅密歐級改裝反艦飛彈型，已退役。",tags=["潛艇","舊式"],form="導彈潛艇（033G）",wiki="Type 033 submarine"),
    s("type-035a","035A型常規潛艇（明級改）","Type 035A Ming-class","Type 035A","submarine",
      aliases=["明級改"],weight="水下約 2,110 噸",length="76 m",crew="57",
      caliber="533mm 魚雷",cap="魚雷/水雷，035 改進批次",mob="常規動力潛艇",
      notes="明級改進批次（電子/武備更新）。",tags=["潛艇"],form="常規潛艇（035A）",wiki="Type 035 submarine"),
    s("type-035b","035B型常規潛艇（明級後期）","Type 035B Ming-class","Type 035B","submarine",
      aliases=["明級後期"],weight="水下約 2,110 噸",length="76 m",crew="57",
      caliber="533mm 魚雷",cap="035 後期改進型",mob="常規動力潛艇",
      notes="明級後期改進型。",tags=["潛艇"],form="常規潛艇（035B）",wiki="Type 035 submarine"),
    s("type-035g","035G型常規潛艇","Type 035G Ming-class","Type 035G","submarine",
      aliases=["明級035G"],weight="水下約 2,110 噸",length="76 m",crew="57",
      caliber="533mm 魚雷",cap="035G 批次，聲納/武備更新",mob="常規動力潛艇",
      notes="明級 035G 批次。",tags=["潛艇"],form="常規潛艇（035G）",wiki="Type 035 submarine"),
    s("type-039g","039G型常規潛艇（宋級改）","Type 039G Song-class","Type 039G","submarine",
      aliases=["宋級改","Song G"],weight="水下約 2,250 噸",length="74.9 m",crew="60",
      caliber="533mm 魚雷",cap="YJ-82 潛射反艦、魚雷",mob="常規動力潛艇",
      notes="宋級量產改進型。",tags=["潛艇"],form="常規潛艇（039G）",wiki="Type 039 submarine"),
    s("kilo-636","基洛級潛艇（636 改進型）","Improved Kilo (Project 636)","Project 636","submarine",
      aliases=["Kilo 636","改進基洛"],weight="水下約 3,100 噸",length="73.8 m",crew="52",
      caliber="533mm 魚雷",cap="Club-S（3M-54E）潛射反艦、魚雷/水雷",mob="常規動力潛艇（俄製）",
      notes="改進基洛級（636/636M），裝備俱樂部飛彈。",tags=["潛艇","俄製"],form="常規潛艇（基洛636）",wiki="Kilo-class submarine"),
    s("jl-1","巨浪-1 潛射彈道飛彈","JL-1 SLBM","JL-1","ballistic",cat="weapon",
      aliases=["巨浪1","JL-1","CSS-N-3"],caliber="潛射彈道飛彈",cap="射程約 1,700 km，092 配備（已退役）",
      mob="固體兩級潛射",notes="巨浪-1，中國第一代潛射彈道飛彈，已退役。",tags=["SLBM","歷史"],form="潛射彈道飛彈（JL-1）",wiki="JL-1"),
    # 兩棲
    s("type-071e","071E型船塢登陸艦（外銷）","Type 071E export LPD","Type 071E","amphibious_ship",
      aliases=["071E"],weight="滿載約 25,000 噸",length="210 m",crew="—",
      cap="船塢登陸艦外銷型（泰國）",mob="船塢登陸艦（LPD）",notes="071 外銷型船塢登陸艦。",
      tags=["兩棲","外銷"],form="船塢登陸艦（LPD，外銷）",wiki="Type 071 amphibious transport dock"),
    s("type-072","072型坦克登陸艦（玉康級）","Type 072 Yukan-class","Type 072","amphibious_ship",
      aliases=["玉康級","Yukan"],weight="滿載約 4,170 噸",length="120 m",crew="—",
      cap="約 10 戰車/500 兵，早期大型登陸艦",mob="坦克登陸艦（LST，已退役）",notes="玉康級坦克登陸艦，早期型。",
      tags=["登陸艦","舊式"],form="坦克登陸艦（玉康級）",wiki="Type 072 landing ship"),
    s("type-072ii","072II型坦克登陸艦（玉亭I級）","Type 072II Yuting I","Type 072II","amphibious_ship",
      aliases=["玉亭I","Yuting I"],weight="滿載約 4,800 噸",length="119 m",crew="104",
      cap="戰車/兵員、直升機甲板",mob="坦克登陸艦（LST）",notes="玉亭I級坦克登陸艦。",
      tags=["登陸艦","兩棲"],form="坦克登陸艦（玉亭I）",wiki="Type 072 landing ship"),
    s("type-073a","073A型中型登陸艦（玉登/雲舒級）","Type 073A Yunshu-class","Type 073A","amphibious_ship",
      aliases=["雲舒級","Yunshu"],weight="滿載約 2,000 噸",length="87 m",crew="—",
      cap="裝載戰車/物資，可搶灘",mob="中型登陸艦（LSM）",notes="玉登/雲舒級中型登陸艦。",
      tags=["登陸艦","兩棲"],form="中型登陸艦（073A）",wiki="Type 073 landing ship"),
    s("type-074a","074A型登陸艦（玉海級）","Type 074A Yuhai-class","Type 074A","amphibious_ship",
      aliases=["玉海級","Yuhai"],weight="滿載約 800 噸",length="58.4 m",crew="—",
      cap="裝甲車/兵員登陸",mob="通用登陸艇（LCU）",notes="玉海級通用登陸艇改進型。",
      tags=["登陸艇","兩棲"],form="通用登陸艇（074A）",wiki="Type 074 landing ship"),
    s("type-271","271型登陸艇（雲南級）","Type 271 Yunnan-class LCU","Type 271","amphibious_ship",
      aliases=["雲南級","Yunnan"],weight="滿載約 135 噸",length="—",crew="—",
      cap="通用登陸艇，大量裝備、可艦載",mob="通用登陸艇（LCU）",notes="雲南級通用登陸艇，量大。",
      tags=["登陸艇","兩棲"],form="通用登陸艇（271）",wiki="Yunnan-class landing craft"),
    s("type-726a","726A型氣墊登陸艇（玉義級改）","Type 726A Yuyi-class LCAC","Type 726A","amphibious_ship",
      aliases=["玉義級改","Yuyi A"],weight="滿載約 160 噸",length="33 m",crew="5",
      cap="1 主戰坦克或兵員，071/075 塢載",mob="氣墊登陸艇（LCAC）",notes="726 氣墊登陸艇改進型。",
      tags=["氣墊艇","兩棲"],form="氣墊登陸艇（726A）",wiki="Type 726 LCAC"),
    s("zubr","野牛級氣墊登陸艇（1232.2）","Zubr-class LCAC","Zubr","amphibious_ship",
      aliases=["野牛級","Zubr","1232.2"],weight="滿載約 555 噸",length="57 m",crew="31",
      cap="3 主戰坦克或 500 兵，大型氣墊登陸艇",mob="大型氣墊登陸艇（LCAC）",notes="野牛級大型氣墊登陸艇（烏克蘭引進/國產）。",
      tags=["氣墊艇","兩棲"],form="大型氣墊登陸艇（野牛級）",wiki="Zubr-class LCAC"),
    s("type-067","067型登陸艇（玉南級）","Type 067 Yunnan early","Type 067","amphibious_ship",
      aliases=["玉南級"],weight="滿載約 135 噸",length="24.8 m",crew="—",
      cap="小型登陸艇（舊式）",mob="小型登陸艇（已退役）",notes="067 早期小型登陸艇。",
      tags=["登陸艇","舊式"],form="小型登陸艇（067）",wiki="Type 067 landing craft"),
    # 掃雷/獵雷
    s("type-081a","081A型獵掃雷艦（渦藏改）","Type 081A Wozang improved","Type 081A","minesweeper",
      aliases=["渦藏改","Wozang A"],weight="滿載約 600 噸",length="55 m",crew="—",
      cap="獵雷聲納、遙控獵雷具",mob="獵掃雷艦（MHC）",notes="081 改進型獵掃雷艦。",
      tags=["掃雷","獵雷"],form="獵掃雷艦（081A）",wiki="Type 081 minesweeper"),
    s("type-082i","082I型掃雷艇（渦掃改）","Type 082I Wosao improved","Type 082I","minesweeper",
      aliases=["渦掃改"],weight="滿載約 400 噸",length="44.8 m",crew="—",
      cap="機械/電磁/聲掃雷具",mob="掃雷艇（MSC）",notes="082 改進型掃雷艇。",
      tags=["掃雷"],form="掃雷艇（082I）",wiki="Type 082 minesweeper"),
    s("type-082ii","082II型獵雷艦（渦陽級）","Type 082II Wozang MCMV","Type 082II","minesweeper",
      aliases=["渦陽級"],weight="滿載約 1,200 噸",length="—",crew="—",
      cap="綜合獵雷/掃雷、遙控獵雷器",mob="獵掃雷艦（MCMV）",notes="082II 較新綜合獵掃雷艦。",
      tags=["獵雷","掃雷"],form="綜合獵掃雷艦（082II）",wiki="Type 082 minesweeper"),
    s("type-010","010型掃雷艦（T-43 系）","Type 010 (T-43 type)","Type 010","minesweeper",
      aliases=["T-43","010型"],weight="滿載約 590 噸",length="60 m",crew="—",
      cap="蘇式 T-43 掃雷艦仿製（舊式）",mob="掃雷艦（已退役）",notes="010 型掃雷艦（蘇聯 T-43 衍生），已退役。",
      tags=["掃雷","舊式"],form="掃雷艦（T-43 系）",wiki="T43-class minesweeper"),
    s("type-312","312型掃雷艇","Type 312 minesweeper","Type 312","minesweeper",
      aliases=["312型"],weight="滿載約 50 噸",length="—",crew="—",
      cap="小型遙控/近岸掃雷艇",mob="小型掃雷艇",notes="312 型小型掃雷艇。",
      tags=["掃雷"],form="小型掃雷艇（312）",wiki="Type 312 minesweeper"),
    # 補給
    s("type-903","903型綜合補給艦（福池級）","Type 903 Fuchi-class AOR","Type 903","replenishment",
      aliases=["福池級","Fuchi"],weight="滿載約 23,000 噸",length="178.5 m",crew="130",
      cap="燃油/彈藥/乾貨橫向補給，遠洋主力",mob="綜合補給艦（AOR）",notes="福池級綜合補給艦，遠洋補給主力（903/903A）。",
      tags=["補給艦","AOR"],form="綜合補給艦（福池級）",wiki="Type 903 replenishment ship"),
    s("type-904b","904B型補給艦（大運級改）","Type 904B Dayun","Type 904B","replenishment",
      aliases=["大運級改"],weight="滿載約 15,000 噸",length="156 m",crew="—",
      cap="島礁補給、乾貨/物資",mob="島礁補給艦（AKS）",notes="904 後期改進批次，南海島礁後勤。",
      tags=["補給艦","後勤"],form="島礁補給艦（904B）",wiki="Type 904 replenishment ship"),
    s("type-908","908型綜合補給艦（青海湖艦）","Type 908 Fusu / Qinghaihu","Type 908","replenishment",
      aliases=["青海湖","Fusu"],weight="滿載約 37,000 噸",length="188 m",crew="—",
      cap="大型油水補給（蘇制商船改裝）",mob="綜合補給艦（AOR）",notes="青海湖艦，蘇制商船改裝的大型補給艦（單艦）。",
      tags=["補給艦","AOR"],form="大型綜合補給艦（908）",wiki="Type 908 replenishment ship"),
    # 電偵/測量
    s("type-815","815型電子偵察船（東調級）","Type 815 Dongdiao-class AGI","Type 815","survey_ship",
      aliases=["東調級","Dongdiao"],weight="滿載約 6,000 噸",length="130 m",crew="250",
      cap="電子/信號情報偵察（ELINT/SIGINT）",mob="電子偵察船（AGI）",notes="東調級電子偵察船，基型。",
      tags=["電子偵察","AGI"],form="電子偵察船（815）",wiki="Dongdiao-class surveillance ship"),
    s("type-815g","815G型電子偵察船","Type 815G AGI","Type 815G","survey_ship",
      aliases=["815G"],weight="滿載約 6,000 噸",length="130 m",crew="—",
      cap="電子/信號情報偵察改進型",mob="電子偵察船（AGI）",notes="東調級後期改進批次。",
      tags=["電子偵察","AGI"],form="電子偵察船（815G）",wiki="Dongdiao-class surveillance ship"),
    s("type-927","927型海洋監視船（拖曳陣）","Type 927 ocean surveillance","Type 927","survey_ship",
      aliases=["927型"],weight="滿載約 5,000 噸",length="—",crew="—",
      cap="拖曳陣列聲納、反潛海洋監視（類 T-AGOS）",mob="海洋監視船（AGOS）",notes="927 型拖曳陣海洋監視船，反潛偵測。",
      tags=["海洋監視","反潛"],form="海洋監視船（AGOS）",wiki="Type 927 surveillance ship"),
    s("type-639","639型水文測量船","Type 639 hydrographic ship","Type 639","survey_ship",
      aliases=["639型"],weight="—",length="—",crew="—",cap="水文/氣象調查測量",mob="水文測量船",
      notes="639 型水文氣象測量船。",tags=["測量船","水文"],form="水文測量船（639）",wiki=""),
    s("type-636-survey","636型海洋測量船","Type 636 survey ship","Type 636","survey_ship",
      aliases=["636型","竺可楨"],weight="滿載約 5,900 噸",length="129 m",crew="—",
      cap="海洋綜合調查測量、聲納測繪",mob="海洋測量船（AGS）",notes="636/636A 海洋綜合測量船。",
      tags=["測量船","海洋調查"],form="海洋測量船（636）",wiki="Type 636A survey ship"),
    # 遠望
    s("yuanwang-7","遠望7號航天測量船","Yuan Wang 7","Yuan Wang 7","survey_ship",
      aliases=["遠望7","Yuan Wang 7"],weight="滿載約 27,000 噸",length="225 m",crew="—",
      cap="航天測控天線、衛星/飛彈彈道測量",mob="航天遠洋測量船",notes="遠望7號新一代航天測控船。",
      tags=["測量船","航天測控"],form="航天遠洋測量船（遠望7）",wiki="Yuanwang"),
    s("yuanwang-2122","遠望21／22號火箭運輸船","Yuan Wang 21/22 rocket transport","Yuan Wang 21","survey_ship",
      aliases=["遠望21","遠望22"],weight="滿載約 9,080 噸",length="130 m",crew="—",
      cap="長征火箭海上運輸（往文昌發射場）",mob="火箭運輸船",notes="遠望21/22 航天火箭海上運輸船。",
      tags=["運輸船","航天"],form="火箭運輸船（遠望21/22）",wiki="Yuanwang"),
    # 援潛救生
    s("type-926","926型潛艇支援救援艦（大江級）","Type 926 Dajiang-class ASR","Type 926","auxiliary",
      aliases=["大江級","Dajiang"],weight="滿載約 9,500 噸",length="156 m",crew="—",
      cap="搭載 LR-7 深潛救生艇、潛艇救援",mob="潛艇支援救援艦（ASR）",notes="大江級潛艇支援救援艦（新型）。",
      tags=["潛艇救援","ASR"],form="潛艇支援救援艦（926）",wiki="Type 926 submarine support ship"),
    s("type-922","922型救生打撈船","Type 922 salvage/rescue","Type 922","auxiliary",
      aliases=["922型","大浪級"],weight="滿載約 4,000 噸",length="—",crew="—",
      cap="海上救生/打撈支援",mob="救生打撈船",notes="922 型救生打撈船（大浪級）。",
      tags=["救生","打撈"],form="救生打撈船（922）",wiki="Type 922 salvage ship"),
    s("type-917","917型援潛救生船","Type 917 submarine rescue","Type 917","auxiliary",
      aliases=["917型"],weight="滿載約 7,000 噸",length="—",crew="—",
      cap="援潛救生、深潛器母船",mob="援潛救生船（ASR）",notes="917 型較新援潛救生船。",
      tags=["潛艇救援","ASR"],form="援潛救生船（917）",wiki=""),
    s("lr7-dsrv","LR7 深潛救生艇","LR7 DSRV","LR7","auxiliary",
      aliases=["LR7","深潛救生艇","DSRV"],weight="約 25 噸",length="約 8 m",crew="2＋18",
      cap="深潛對接救援落難潛艇艇員，母艦搭載",mob="深潛救生載具（DSRV）",notes="LR7 深潛救生艇，由 926 等母艦搭載。",
      tags=["深潛救生","DSRV"],form="深潛救生艇（LR7）",wiki="LR7"),
    # 破冰船
    s("haibing-722","海冰722破冰船","Haibing 722 icebreaker","Haibing 722","auxiliary",
      aliases=["海冰722"],weight="滿載約 4,860 噸",length="103 m",crew="—",
      cap="海軍破冰、極地/渤海冰區支援",mob="破冰船",notes="海冰722海軍破冰船。",
      tags=["破冰船"],form="海軍破冰船（海冰722）",wiki=""),
    s("xuelong2","雪龍2號極地破冰船","Xuelong 2 polar icebreaker","Xuelong 2","auxiliary",
      aliases=["雪龍2","Xuelong 2"],weight="滿載約 13,990 噸",length="122.5 m",crew="科考 90",
      cap="極地科考、雙向破冰（軍民融合任務參考）",mob="極地破冰科考船",notes="雪龍2號國產極地破冰科考船（極地研究，軍民融合參考）。",
      tags=["破冰船","極地"],form="極地破冰科考船（雪龍2）",wiki="MV Xue Long 2"),
    # 訓練/試驗
    s("zhenghe","鄭和艦遠洋訓練艦（Type 0891A）","Zheng He training ship","Type 0891A","auxiliary",
      aliases=["鄭和艦","Zheng He"],weight="滿載約 6,000 噸",length="132 m",crew="學員 200+",
      cap="海軍院校遠洋航海實習訓練",mob="遠洋訓練艦",notes="鄭和艦遠洋航海訓練艦，多次環球訪問。",
      tags=["訓練艦"],form="遠洋訓練艦（鄭和）",wiki="Chinese training ship Zheng He"),
    s("qijiguang","戚繼光艦遠洋訓練艦（Type 680）","Qi Jiguang training ship","Type 680","auxiliary",
      aliases=["戚繼光艦","Qi Jiguang"],weight="滿載約 9,000 噸",length="163 m",crew="學員 400+",
      cap="新型綜合遠洋訓練艦，可搭直升機",mob="遠洋訓練艦",notes="戚繼光艦新型遠洋訓練艦。",
      tags=["訓練艦"],form="遠洋訓練艦（戚繼光）",wiki="Chinese training ship Qi Jiguang"),
    s("shichang","世昌艦國防動員艦（Type 89）","Shichang defense mobilization ship","Type 89","auxiliary",
      aliases=["世昌艦","Shichang"],weight="滿載約 10,000 噸",length="120 m",crew="—",
      cap="訓練/醫療/滾裝運輸多用途、國防動員",mob="多用途訓練/動員艦",notes="世昌艦多用途國防動員艦（訓練/醫療/滾裝）。",
      tags=["訓練艦","動員"],form="多用途國防動員艦（世昌）",wiki="Chinese ship Shichang"),
    s("type-910","910型試驗艦","Type 910 trials ship","Type 910","auxiliary",
      aliases=["910型"],weight="—",length="—",crew="—",cap="裝備/武器試驗輔助平台",mob="試驗輔助艦",
      notes="910 型試驗艦，裝備海試支援。",tags=["試驗艦"],form="試驗輔助艦（910）",wiki=""),
    # 海警
    s("ccg-3901","海警3901大型巡邏艦","CCG 3901 (Zhaotou-class)","CCG 3901","coast_guard",
      aliases=["海警3901","昭頭級"],weight="滿載約 12,000 噸",length="165 m",crew="—",
      cap="76mm 砲＋副砲，萬噸級海警執法（昭頭級姐妹艦）",mob="大型海警執法船",notes="海警3901，昭頭級萬噸海警船（2901 姐妹艦）。",
      tags=["海警","執法"],form="大型海警巡防船（CG cutter）",wiki="Zhaotou-class patrol vessel"),
    s("type-718b","718B型海警巡邏船","Type 718B CCG cutter","Type 718B","coast_guard",
      aliases=["718B"],weight="滿載約 4,000 噸",length="—",crew="—",
      cap="遠海維權執法巡邏（76mm 主砲）",mob="海警巡防船",notes="718B 型海警巡防船。",
      tags=["海警","執法"],form="海警巡防船（CG cutter）",wiki="China Coast Guard"),
]

if __name__ == "__main__":
    total, n = merge(GX1)
    print(f"GX1 海軍補漏：{n} 筆；累計 {total}")
    total, n = merge(GX2)
    print(f"GX2 海軍補漏：{n} 筆；new_items_extra.json 現有 {total} 筆")
