#!/usr/bin/env python3
"""Grok 交叉比對後補漏的批次；沿用 expand_batches 的 mk/merge，累加到 new_items_extra.json。"""
from expand_batches import mk, W, merge

# ===== GX1：海軍缺漏（Grok naval_1 diff）=====
GX1 = [
    # 早期/變體驅逐艦
    mk("type-052","052型驅逐艦（旅滬級）","Type 052 Luhu-class","Type 052","warship","海軍",
       aliases=["旅滬級","Luhu","哈爾濱","青島"],weight="滿載約 4,800 噸",length="144 m",crew="260",
       caliber="100mm 砲",cap="8×YJ-83 反艦、HQ-7 防空、2 架直升機",mob="驅逐艦（DDG）",branch_hint="海軍",
       notes="旅滬級驅逐艦（哈爾濱/青島），首用燃氣渦輪與西方技術的過渡型。",tags=["驅逐艦"],
       form_zh="飛彈驅逐艦（旅滬級）",wiki="Type 052 destroyer"),
    mk("type-051dt","051DT型驅逐艦（旅大III級）","Type 051DT Luda III","Type 051DT","warship","海軍",
       aliases=["旅大III","Luda III"],weight="滿載約 3,730 噸",length="132 m",crew="280",
       caliber="2×2 130mm 砲",cap="YJ-8 反艦、防空改良",mob="驅逐艦（DDG，已退役）",branch_hint="海軍",
       notes="旅大級後期改良型（防空/電子升級），已退役。",tags=["驅逐艦","舊式"],
       form_zh="飛彈驅逐艦（旅大III）",wiki="Type 051 destroyer"),
    mk("type-051g","051G型驅逐艦（旅大IV級）","Type 051G Luda IV","Type 051G","warship","海軍",
       aliases=["旅大IV","Luda IV","湛江"],weight="滿載約 3,730 噸",length="132 m",crew="280",
       caliber="2×2 130mm 砲",cap="YJ-8 反艦、武器/雷達更新",mob="驅逐艦（DDG，已退役）",branch_hint="海軍",
       notes="旅大級末期升級型，已退役。",tags=["驅逐艦","舊式"],
       form_zh="飛彈驅逐艦（旅大IV）",wiki="Type 051 destroyer"),
    mk("type-055a","055A型驅逐艦（改進型，研發中）","Type 055A (reported)","Type 055A","warship","海軍",
       aliases=["055A","Renhai improved"],weight="—",length="—",crew="—",
       caliber="130mm 砲",cap="112 垂發、改進推進/感測（外界討論）",mob="大型驅逐艦（後續批次）",branch_hint="海軍",
       notes="055 改進/後續批次，公開討論中，諸元推測。",tags=["驅逐艦","研發中"],
       form_zh="大型飛彈驅逐艦（055 改進）",wiki="Type 055 destroyer"),
    mk("sovremenny-em","現代級驅逐艦（956EM）","Sovremenny 956EM","Project 956EM","warship","海軍",
       aliases=["956EM","泰州","寧波"],weight="滿載約 7,940 噸",length="156 m",crew="296",
       caliber="2×2 130mm 砲",cap="8×3M-80MBE 日炙超音速反艦、施基利防空",mob="驅逐艦（俄製改進）",branch_hint="海軍",
       notes="現代級改進型（泰州/寧波），強化反艦與防空。",tags=["驅逐艦","俄製"],
       form_zh="飛彈驅逐艦（956EM）",wiki="Sovremenny-class destroyer"),
    # 早期護衛艦
    mk("type-065","065型護衛艦（江南級）","Type 065 Jiangnan-class","Type 065","warship","海軍",
       aliases=["江南級","Jiangnan"],weight="滿載約 1,600 噸",length="90 m",crew="175",
       caliber="3×100mm 砲",cap="火砲護衛艦（無反艦飛彈）",mob="護衛艦（FF，已退役）",branch_hint="海軍",
       notes="江南級護衛艦，早期國產火砲護衛艦，已退役。",tags=["護衛艦","舊式"],
       form_zh="火砲護衛艦（江南級）",wiki="Type 065 frigate"),
    mk("type-053k","053K型護衛艦（江東級）","Type 053K Jiangdong-class","Type 053K","warship","海軍",
       aliases=["江東級","Jiangdong"],weight="滿載約 1,900 噸",length="103 m",crew="—",
       caliber="2×2 100mm 砲",cap="HQ-61 艦空飛彈試驗（首型防空護衛艦）",mob="護衛艦（FFG，已退役）",branch_hint="海軍",
       notes="江東級防空護衛艦，HQ-61 艦空飛彈試驗艦，已退役。",tags=["護衛艦","防空","舊式"],
       form_zh="防空護衛艦（江東級）",wiki="Type 053K frigate"),
    # 巡邏/近岸
    mk("type-037i","037I型獵潛艇（海青級基型）","Type 037I Haiqing-class","Type 037I","patrol_boat","海軍",
       aliases=["海青級","Haiqing"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm＋2×2 14.5mm",cap="反潛火箭深彈、近岸反潛巡邏",mob="近岸獵潛艇",branch_hint="海軍",
       notes="海青級獵潛艇基型（037 反潛改良）。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-037ig","037IG型飛彈艇（紅星級）","Type 037IG Houxin-class","Type 037IG","patrol_boat","海軍",
       aliases=["紅星級","Houxin"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm",cap="4×YJ-8 反艦飛彈（037 平台加裝反艦）",mob="近岸飛彈艇",branch_hint="海軍",
       notes="紅星級飛彈艇，037 加裝反艦飛彈的近岸型。",tags=["飛彈艇","近岸"],
       form_zh="近岸飛彈艇（PGG）",wiki="Houxin-class missile boat"),
    mk("type-026","026型魚雷艇（滬川級）","Type 026 Huchuan-class","Type 026","patrol_boat","海軍",
       aliases=["滬川級","Huchuan"],weight="滿載約 45 噸",length="21.8 m",crew="23",
       caliber="2×2 14.5mm",cap="2×533mm 魚雷、水翼高速",mob="水翼魚雷艇（舊式）",branch_hint="海軍",
       notes="滬川級水翼魚雷艇，冷戰近海打擊，已退役。",tags=["魚雷艇","水翼","舊式"],
       form_zh="水翼魚雷艇（舊式）",wiki="Huchuan-class torpedo boat"),
    mk("type-062i","062I型護衛艇（上海III級）","Type 062I Shanghai III","Type 062I","patrol_boat","海軍",
       aliases=["上海III","Shanghai II/III"],weight="滿載約 170 噸",length="41 m",crew="43",
       caliber="2×2 37mm＋2×2 25mm",cap="近岸巡邏/護衛（062 改進）",mob="近岸砲艇",branch_hint="海軍",
       notes="上海級改進型近岸巡邏砲艇。",tags=["砲艇","近岸","舊式"],
       form_zh="近岸巡邏砲艇（改進）",wiki="Shanghai-class gunboat"),
    # 艦載反艦飛彈
    mk("yj-8","鷹擊-8 反艦飛彈（C-801）","YJ-8 / C-801","YJ-8","asm","海軍",cat="weapon",
       aliases=["YJ-8","C-801","鷹擊8"],rng="約 42 km",caliber="反艦飛彈",cap="固體火箭、掠海亞音速、165kg 戰鬥部",
       mob="Mach 0.9；艦/岸射",branch_hint="海軍",notes="鷹擊-8 第一代國產掠海反艦飛彈（Exocet 級）。",
       tags=["反艦","亞音速"],form_zh="反艦飛彈（YJ-8）",wiki="YJ-8"),
    mk("yj-82","鷹擊-82 潛射反艦飛彈","YJ-82 sub-launched","YJ-82","asm","海軍",cat="weapon",
       aliases=["YJ-82","鷹擊82"],rng="約 40 km",caliber="潛射反艦飛彈",cap="潛艇魚雷管發射、掠海亞音速",
       mob="Mach 0.9；潛射",branch_hint="海軍",notes="鷹擊-8 的潛射型（潛艇發射反艦飛彈）。",
       tags=["反艦","潛射"],form_zh="潛射反艦飛彈（YJ-82）",wiki="YJ-8"),
    mk("yj-83k","鷹擊-83K 空射反艦飛彈","YJ-83K air-launched","YJ-83K","asm","海軍",cat="weapon",
       aliases=["YJ-83K","鷹擊83K"],rng="約 200 km（空射增程）",caliber="空射反艦飛彈",cap="渦噴、末端 Mach 1.4；海航 JH-7/H-6 掛載",
       mob="亞音速掠海；空射",branch_hint="海軍",notes="鷹擊-83 空射型，海軍航空兵對海打擊主力。",
       tags=["反艦","空射"],form_zh="空射反艦飛彈（YJ-83K）",wiki="YJ-83"),
    mk("yj-18b","鷹擊-18B 潛射反艦飛彈","YJ-18B sub-launched","YJ-18B","asm","海軍",cat="weapon",
       aliases=["YJ-18B","鷹擊18B"],rng="約 540 km",caliber="潛射反艦巡航飛彈",cap="潛艇發射、末端超音速衝刺",
       mob="次音速+超音速末端；潛射",branch_hint="海軍",notes="鷹擊-18 潛射型，元/商級潛艇裝備。",
       tags=["反艦","潛射"],form_zh="潛射反艦巡航飛彈（YJ-18B）",wiki="YJ-18"),
    mk("c-705","C-705 反艦飛彈","C-705","C-705","asm","海軍",cat="weapon",
       aliases=["C-705"],rng="約 75–140 km",caliber="輕型反艦飛彈",cap="快艇/直升機/岸射，雷達/電視導引",
       mob="亞音速掠海",branch_hint="海軍",notes="C-705 輕型反艦飛彈（外銷），小型載台適用。",
       tags=["反艦","外銷"],form_zh="輕型反艦飛彈（C-705）",wiki="C-705"),
    mk("c-704","C-704 反艦飛彈","C-704","C-704","asm","海軍",cat="weapon",
       aliases=["C-704"],rng="約 35 km",caliber="輕型反艦飛彈",cap="快艇用、電視/雷達導引",
       mob="亞音速掠海",branch_hint="海軍",notes="C-704 輕型反艦飛彈（外銷）。",
       tags=["反艦","外銷"],form_zh="輕型反艦飛彈（C-704）",wiki="C-704"),
    # 艦空飛彈
    mk("hhq-7","海紅旗-7 艦空飛彈","HHQ-7 / FM-90N","HHQ-7","sam","海軍",cat="weapon",
       aliases=["HHQ-7","海紅旗7","FM-90N"],rng="約 8–15 km",caliber="近程艦空飛彈",cap="點防空，053H3/054 等裝備",
       mob="指令/紅外導引",branch_hint="海軍",notes="海紅旗-7 艦載近程防空飛彈（紅旗-7 艦載型）。",
       tags=["艦空飛彈","近程"],form_zh="艦載近程防空飛彈（HHQ-7）",wiki="HQ-7"),
    mk("hhq-10","海紅旗-10 近防飛彈（FL-3000N）","HHQ-10 / FL-3000N","HHQ-10","sam","海軍",cat="weapon",
       aliases=["HHQ-10","海紅旗10","FL-3000N"],rng="約 9 km",caliber="末端近防飛彈",cap="18/24 聯裝、被動雷達+紅外，攔截反艦飛彈",
       mob="發射後鎖定",branch_hint="海軍",notes="海紅旗-10 艦載末端近防飛彈，攔截來襲反艦飛彈。",
       tags=["艦空飛彈","近防"],form_zh="艦載末端近防飛彈（HHQ-10）",wiki="HQ-10"),
    mk("hhq-16bc","海紅旗-16B/C 艦空飛彈","HHQ-16B/C","HHQ-16B","sam","海軍",cat="weapon",
       aliases=["HHQ-16B","HHQ-16C","海紅旗16改"],rng="約 70 km（增程）",caliber="中程艦空飛彈",cap="增程/改進導引，054A/052D 垂發",
       mob="半主動/主動雷達",branch_hint="海軍",notes="海紅旗-16 增程改進型，區域防空射程提升。",
       tags=["艦空飛彈","中程"],form_zh="艦載中程防空飛彈（HHQ-16 改）",wiki="HQ-16"),
    mk("hhq-9b","海紅旗-9B 艦空飛彈","HHQ-9B","HHQ-9B","sam","海軍",cat="weapon",
       aliases=["HHQ-9B","海紅旗9B"],rng="約 200+ km",caliber="遠程艦空飛彈",cap="增程/反彈道改進，052D/055 裝備",
       mob="慣性+主動雷達末端",branch_hint="海軍",notes="海紅旗-9 艦載增程型，遠程區域防空/反彈道。",
       tags=["艦空飛彈","遠程"],form_zh="艦載遠程防空飛彈（HHQ-9B）",wiki="HQ-9"),
    mk("rif-m","裡夫-M 艦空飛彈系統","Rif-M / S-300FM","Rif-M","sam","海軍",cat="weapon",
       aliases=["Rif-M","S-300FM","SA-N-20","裡夫"],rng="約 150 km",caliber="遠程艦空飛彈（俄製）",cap="051C 裝備、48N6 導彈、遠程區域防空",
       mob="半主動雷達",branch_hint="海軍",notes="俄製裡夫-M（S-300F 海軍型），裝備 051C 驅逐艦。",
       tags=["艦空飛彈","俄製"],form_zh="艦載遠程防空飛彈（Rif-M）",wiki="S-300 missile system"),
    mk("shtil","施基利 艦空飛彈系統","Shtil / 9M38","Shtil","sam","海軍",cat="weapon",
       aliases=["Shtil","9M38","SA-N-12","施基利"],rng="約 30–50 km",caliber="中程艦空飛彈（俄製）",cap="052B 裝備、單臂發射、中程防空",
       mob="半主動雷達",branch_hint="海軍",notes="俄製施基利中程艦空飛彈，裝備 052B 驅逐艦。",
       tags=["艦空飛彈","俄製"],form_zh="艦載中程防空飛彈（施基利）",wiki="9K37 Buk"),
    # 魚雷
    mk("yu-8","魚-8 火箭助飛魚雷","Yu-8 ASROC-type","Yu-8","torpedo","海軍",
       aliases=["Yu-8","魚8","CY-5"],rng="射程約 30–50 km",caliber="反潛飛彈/助飛魚雷",cap="垂發、火箭助推＋輕型魚雷，遠程反潛",
       mob="火箭助飛",branch_hint="海軍",notes="魚-8 火箭助飛魚雷（類 ASROC），055/052D 垂發反潛。",
       tags=["反潛","助飛魚雷"],form_zh="火箭助飛反潛魚雷（ASROC 型）",wiki="CY-5"),
    mk("yu-9","魚-9 魚雷","Yu-9 torpedo","Yu-9","torpedo","海軍",
       aliases=["Yu-9","魚9"],rng="—",caliber="通用魚雷",cap="新型輕/通用魚雷（公開型號）",
       mob="聲導",branch_hint="海軍",notes="魚-9 新型魚雷（公開資料有限）。",
       tags=["魚雷"],form_zh="通用魚雷",wiki="Chinese torpedo"),
    # 艦炮
    mk("hpj-38","H/PJ-38 型 130mm 艦炮","H/PJ-38 130mm naval gun","H/PJ-38","naval_gun","海軍",cat="weapon",
       aliases=["H/PJ-38","130mm 艦砲"],caliber="130mm/70 單管",rng="射程約 30 km（增程彈更遠）",
       cap="對海/對空/對岸、可射制導砲彈；052D/055 主砲",mob="全自動艦砲",branch_hint="海軍",
       notes="H/PJ-38 單管 130mm 艦砲，052D/055 主砲。",tags=["艦炮","130mm"],
       form_zh="130mm 艦炮（主砲）",wiki="H/PJ-38"),
    mk("hpj-26","H/PJ-26 型 76mm 艦炮","H/PJ-26 76mm naval gun","H/PJ-26","naval_gun","海軍",cat="weapon",
       aliases=["H/PJ-26","76mm 艦砲","AK-176 衍生"],caliber="76mm 單管",rng="射程約 16 km",
       cap="高射速對海/對空；054A/056 等主砲",mob="全自動艦砲",branch_hint="海軍",
       notes="H/PJ-26 76mm 艦砲（俄 AK-176 衍生），054A/056 主砲。",tags=["艦炮","76mm"],
       form_zh="76mm 艦炮",wiki="H/PJ-26"),
    # 艦載雷達
    mk("type-346","346型有源相控陣雷達（龍眼）","Type 346 Dragon Eye AESA","Type 346","naval_radar","海軍",cat="equipment",
       aliases=["346型","Dragon Eye","海之星"],cap="四面固定相控陣、對空/對海/火控，052C 裝備",
       sensors="S 波段有源相控陣（AESA）",mob="艦載固定四面陣",branch_hint="海軍",
       notes="346 型「海之星」相控陣雷達（龍眼），中華神盾核心，052C 裝備。",tags=["艦載雷達","相控陣"],
       form_zh="艦載有源相控陣雷達（346）",wiki="Type 346 radar"),
    mk("type-346a","346A型相控陣雷達","Type 346A AESA","Type 346A","naval_radar","海軍",cat="equipment",
       aliases=["346A型"],cap="052D 改進相控陣，探測距離/多目標能力提升",
       sensors="改進型有源相控陣",mob="艦載四面陣",branch_hint="海軍",
       notes="346A 相控陣雷達，052D 裝備，較 346 改進。",tags=["艦載雷達","相控陣"],
       form_zh="艦載相控陣雷達（346A）",wiki="Type 346 radar"),
    mk("type-346b","346B型大型相控陣雷達","Type 346B AESA","Type 346B","naval_radar","海軍",cat="equipment",
       aliases=["346B型"],cap="055 大型四面陣，雙波段配合，遠程對空/反彈道",
       sensors="大型有源相控陣",mob="艦載大型四面陣",branch_hint="海軍",
       notes="346B 大型相控陣雷達，055 驅逐艦裝備。",tags=["艦載雷達","相控陣"],
       form_zh="艦載大型相控陣雷達（346B）",wiki="Type 346 radar"),
    mk("type-382","382型三坐標對空雷達","Type 382 3D radar","Type 382","naval_radar","海軍",cat="equipment",
       aliases=["382型","Sea Eagle"],cap="054A 等三坐標對空搜索雷達",
       sensors="三坐標對空搜索雷達",mob="艦載旋轉天線",branch_hint="海軍",
       notes="382 型三坐標對空搜索雷達（俄 Fregat 衍生），054A 裝備。",tags=["艦載雷達","三坐標"],
       form_zh="艦載三坐標對空雷達（382）",wiki="Type 382 radar"),
]

if __name__ == "__main__":
    total, n = merge(GX1)
    print(f"GX1 海軍補漏：{n} 筆；new_items_extra.json 現有 {total} 筆")
