#!/usr/bin/env python3
"""資料庫全面擴充：分批把新型號寫入 data/new_items_extra.json（依 id 去重、可累加）。
每批以精簡欄位定義，mk() 補上完整結構。諸元為公開資料整理，wiki 供後續抓圖/查證。"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "new_items_extra.json"

def W(title, zh=None):
    return [{"label": f"維基百科：{zh or title}", "url": f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"}]

def mk(id, zh, en, desig, sub, svc, *, cat="vehicle", aliases=None, caliber="—", crew="—",
       weight="—", length="—", rng="—", cap="—", mob="—", sensors="—", armor="—",
       notes="", tags=None, form_zh="", wiki="", sources=None, image="", branch_hint=""):
    d = {
        "id": id, "name_zh": zh, "name_en": en, "designation": desig,
        "aliases": aliases or [], "category": cat, "subcategory": sub,
        "origin": "China", "origin_zh": "中國", "service": svc, "service_zh": svc,
        "caliber": caliber, "crew": crew, "weight_kg": weight, "length_mm": length,
        "range_m": rng, "rate_of_fire": "—", "capacity": cap, "armor": armor,
        "mobility": mob, "sensors": sensors, "notes_zh": notes, "notes_en": "",
        "tags": tags or [], "odin_hint": "", "form_zh": form_zh, "form_en": "",
        "wiki": wiki, "image": image, "odin_url": "https://odin.t2com.army.mil/WEG",
        "sources": sources or (W(wiki) if wiki else []),
    }
    if branch_hint:
        d["branch_hint"] = branch_hint
    return d

# ===== 批次 E4：雷達／電子戰／防空感測 =====
RADAR = [
    mk("jy-27","警戒-27 對空情報雷達","JY-27 Wide Mat radar","JY-27","radar","空軍",cat="equipment",
       aliases=["JY-27","Wide Mat"],rng="探測約 390 km",cap="VHF 波段遠程對空預警、反匿蹤",
       mob="車載/固定",sensors="VHF 2D 對空搜索雷達",branch_hint="空軍",
       notes="JY-27 米波遠程對空情報雷達，具反匿蹤能力。",tags=["雷達","對空預警"],
       form_zh="遠程對空情報雷達（VHF）",wiki="JY-27 radar"),
    mk("ylc-8b","YLC-8B 反隱形雷達","YLC-8B counter-stealth radar","YLC-8B","radar","空軍",cat="equipment",
       aliases=["YLC-8B"],rng="探測約 500 km",cap="UHF 波段、反匿蹤目標偵測",
       mob="車載機動",sensors="UHF 機動反匿蹤雷達",branch_hint="空軍",
       notes="YLC-8B 機動反隱形對空監視雷達。",tags=["雷達","反隱形"],
       form_zh="反隱形對空監視雷達（UHF）",wiki="YLC-8B"),
    mk("slc-7","SLC-7 對空監視雷達","SLC-7 surveillance radar","SLC-7","radar","空軍",cat="equipment",
       aliases=["SLC-7"],rng="探測約 450 km",cap="L 波段多功能三坐標、反匿蹤/反輻射",
       mob="車載機動",sensors="L 波段三坐標 AESA",branch_hint="空軍",
       notes="SLC-7 多功能對空監視雷達。",tags=["雷達","三坐標"],
       form_zh="多功能對空監視雷達（L 波段）",wiki="SLC-7"),
    mk("slc-2","SLC-2 砲兵定位雷達","SLC-2 counter-battery radar","SLC-2","radar","陸軍",cat="equipment",
       aliases=["SLC-2","BL904"],rng="偵測約 35–50 km",cap="敵砲兵/火箭彈道反算、我砲校射",
       mob="車載機動",sensors="相控陣砲位偵測雷達",branch_hint="陸軍",
       notes="SLC-2 砲兵偵察定位雷達（counter-battery）。",tags=["雷達","砲兵偵察"],
       form_zh="砲兵定位雷達（WLR）",wiki="SLC-2 radar"),
    mk("jyl-1","JYL-1 三坐標對空雷達","JYL-1 3D radar","JYL-1","radar","空軍",cat="equipment",
       aliases=["JYL-1"],rng="探測約 300 km",cap="S 波段全固態三坐標",
       mob="車載",sensors="S 波段三坐標雷達",branch_hint="空軍",
       notes="JYL-1 三坐標對空監視雷達。",tags=["雷達","三坐標"],
       form_zh="三坐標對空雷達（S 波段）",wiki="JYL-1"),
    mk("type-120-radar","305A／120 型低空補盲雷達","Type 305A/120 low-altitude radar","Type 120","radar","空軍",cat="equipment",
       aliases=["305A","Type 120"],rng="探測約 200 km",cap="低空/超低空補盲、防空系統火控引導",
       mob="車載機動",sensors="低空補盲三坐標雷達",branch_hint="空軍",
       notes="305A／120 型低空補盲雷達，配合防空系統。",tags=["雷達","低空補盲"],
       form_zh="低空補盲雷達",wiki="Type 305A radar"),
    mk("dwl-002","DWL-002 被動偵測系統","DWL-002 passive ESM/locating system","DWL-002","ew","空軍",cat="equipment",
       aliases=["DWL-002","Kolchuga class"],rng="偵測約 500 km",cap="被動偵測輻射源、不主動發射、反匿蹤定位",
       mob="車載（多站）",sensors="被動電子偵測/定位系統",branch_hint="空軍",
       notes="DWL-002 被動雷達/電子偵測系統，靠敵方輻射源定位。",tags=["電子戰","被動偵測"],
       form_zh="被動電子偵測定位系統（ESM）",wiki="DWL-002"),
    mk("cetc-jammer","車載通信/雷達干擾系統","Ground EW jamming system","EW-jammer","ew","陸軍",cat="equipment",
       aliases=["電子干擾車"],rng="—",cap="通信干擾、雷達壓制、GPS 干擾",
       mob="車載機動",sensors="電子對抗（ECM）",branch_hint="陸軍",
       notes="解放軍地面電子戰干擾系統（型號多樣），壓制敵通信/雷達/導航。",tags=["電子戰","干擾"],
       form_zh="地面電子戰干擾系統（ECM）",wiki="Electronic warfare"),
]

# ===== 批次 E5：飛彈／彈藥變體 =====
MISSILE = [
    mk("pl-9","霹靂-9 近距空對空飛彈","PL-9 short-range AAM","PL-9","aam","空軍",cat="weapon",
       aliases=["PL-9C"],rng="約 22 km",caliber="近距空對空",cap="紅外導引、可頭盔瞄準；亦有地面型",
       mob="Mach 2+",notes="霹靂-9 近距紅外空對空飛彈。",tags=["空對空","近距"],branch_hint="空軍",
       form_zh="近距空對空飛彈（紅外）",wiki="PL-9"),
    mk("pl-11","霹靂-11 半主動空對空飛彈","PL-11 SARH AAM","PL-11","aam","空軍",cat="weapon",
       aliases=["PL-11"],rng="約 40 km",caliber="中距空對空",cap="半主動雷達導引（義大利 Aspide 衍生）",
       mob="Mach 4",notes="霹靂-11 半主動雷達中距空對空飛彈。",tags=["空對空","中距"],branch_hint="空軍",
       form_zh="中距空對空飛彈（SARH）",wiki="PL-11"),
    mk("pl-21","霹靂-21 衝壓遠程空對空飛彈","PL-21 ramjet BVR AAM","PL-21","aam","空軍",cat="weapon",
       aliases=["PL-21"],rng="約 200+ km（推測）",caliber="遠程空對空",cap="衝壓發動機、主動雷達（發展中）",
       mob="衝壓動力高速",notes="霹靂-21 衝壓動力遠程空對空飛彈（發展/推測）。",tags=["空對空","遠程"],branch_hint="空軍",
       form_zh="遠程空對空飛彈（衝壓）",wiki="PL-21"),
    mk("hj-73","紅箭-73 反戰車飛彈","HJ-73 ATGM","HJ-73","atgm","陸軍",cat="weapon",
       aliases=["HJ-73","紅箭73"],rng="約 3 km",caliber="反戰車飛彈",cap="有線導引（AT-3 衍生），穿深約 500mm",
       mob="車載/步兵",notes="紅箭-73 第一代反戰車飛彈（蘇聯 Malyutka 衍生），舊式。",tags=["反戰車","舊式"],
       form_zh="反戰車飛彈（第一代）",wiki="HJ-73"),
    mk("hj-11","紅箭-11 反戰車飛彈","HJ-11 ATGM","HJ-11","atgm","陸軍",cat="weapon",
       aliases=["HJ-11"],rng="約 6 km",caliber="反戰車飛彈",cap="雷射駕束/紅外，串聯 HEAT",
       mob="車載/直升機/步兵",notes="紅箭-11 反戰車飛彈。",tags=["反戰車"],
       form_zh="反戰車飛彈",wiki="HJ-11"),
    mk("hq-2","紅旗-2 防空飛彈（舊式）","HQ-2 SAM","HQ-2","sam","空軍",cat="weapon",
       aliases=["HQ-2","SA-2 衍生"],rng="約 35 km",caliber="中高空防空",cap="無線電指令導引（SA-2 衍生），多已退役",
       mob="固定/牽引陣地",notes="紅旗-2 中高空防空飛彈，蘇聯 SA-2 衍生，逐步退役。",tags=["防空","舊式"],branch_hint="空軍",
       form_zh="中高空防空飛彈（舊式）",wiki="HQ-2"),
    mk("hq-12","紅旗-12（凱山1）防空飛彈","HQ-12 (KS-1) SAM","HQ-12","sam","空軍",cat="weapon",
       aliases=["HQ-12","KS-1","凱山1"],rng="約 50 km",caliber="中程防空",cap="相控陣制導、半主動雷達",
       mob="車載機動",notes="紅旗-12／凱山-1 中程防空飛彈，取代部分 HQ-2。",tags=["防空","中程"],branch_hint="空軍",
       form_zh="中程防空飛彈（KS-1）",wiki="KS-1 (missile)"),
    mk("df-3","東風-3 中程彈道飛彈（歷史）","DF-3 MRBM","DF-3","ballistic","火箭軍",cat="weapon",
       aliases=["DF-3","CSS-2"],rng="約 2,500–4,000 km",caliber="中程彈道飛彈",cap="液體燃料、單彈頭（歷史型，已退役）",
       mob="陣地/機動",notes="東風-3 中程彈道飛彈，早期核威懾（曾外銷沙烏地），已退役。",tags=["彈道飛彈","歷史"],branch_hint="火箭軍",
       form_zh="中程彈道飛彈（歷史）",wiki="DF-3"),
    mk("df-4","東風-4 遠程彈道飛彈（歷史）","DF-4 IRBM/ICBM","DF-4","ballistic","火箭軍",cat="weapon",
       aliases=["DF-4","CSS-3"],rng="約 5,500 km",caliber="遠程彈道飛彈",cap="液體燃料兩級、單核彈頭（歷史型）",
       mob="洞庫/陣地",notes="東風-4 遠程彈道飛彈，早期核威懾，逐步退役。",tags=["彈道飛彈","歷史"],branch_hint="火箭軍",
       form_zh="遠程彈道飛彈（歷史）",wiki="DF-4"),
    mk("df-21c","東風-21C 中程彈道飛彈","DF-21C MRBM","DF-21C","ballistic","火箭軍",cat="weapon",
       aliases=["DF-21C","CSS-5 Mod 3"],rng="約 1,700 km",caliber="中程彈道飛彈",cap="固體燃料、精確對地打擊",
       mob="公路機動 TEL",notes="東風-21C 對地打擊中程彈道飛彈。",tags=["彈道飛彈","中程"],branch_hint="火箭軍",
       form_zh="中程彈道飛彈（對地）",wiki="DF-21"),
    mk("gb-6","GB-6 滑翔制導炸彈","GB-6 glide bomb","GB-6","bomb","空軍",cat="weapon",
       aliases=["GB-6","天雷"],rng="滑翔約 60 km",caliber="制導炸彈",cap="防區外滑翔、子母/整體戰鬥部",
       mob="空投滑翔",notes="GB-6 系列防區外滑翔制導炸彈。",tags=["炸彈","滑翔"],branch_hint="空軍",
       form_zh="滑翔制導炸彈（防區外）",wiki="GB-6"),
    mk("ls-500j","雷石-500J 制導炸彈","LS-500J guided bomb","LS-500J","bomb","空軍",cat="weapon",
       aliases=["LS-500J","雷石500"],rng="投放約 60 km（滑翔）",caliber="500kg 級制導炸彈",cap="衛星/雷射導引",
       mob="空投",notes="雷石-500J 精確制導炸彈。",tags=["炸彈","制導"],branch_hint="空軍",
       form_zh="精確制導炸彈（500kg）",wiki="LS-6"),
]

# ===== 批次 E6：步兵武器／單兵變體 =====
INFANTRY = [
    mk("qbb-95","95式班用機槍","QBB-95 LSW","QBB-95","mg","通用",cat="weapon",
       aliases=["QBB-95","95式班機"],caliber="5.8×42mm",weight="約 3.95 kg",rng="有效 600m",
       cap="75 發彈鼓、無托、與 QBZ-95 同族",mob="—",notes="95式班用輕機槍，槍族通用。",
       tags=["機槍","班用"],form_zh="班用輕機槍（5.8mm）",wiki="QBB-95"),
    mk("qbb-191","191式班用機槍","QBB-191 LSW","QBB-191","mg","通用",cat="weapon",
       aliases=["QBB-191"],caliber="5.8×42mm",weight="約 4.6 kg",rng="有效 600–800m",
       cap="75 發彈鼓/彈匣、191 槍族",mob="—",notes="191 槍族班用機槍。",
       tags=["機槍","班用"],form_zh="班用輕機槍（191 槍族）",wiki="QBZ-191"),
    mk("type-56-sks","56式半自動步槍","Type 56 carbine (SKS)","Type 56","carbine","通用",cat="weapon",
       aliases=["56半","SKS"],caliber="7.62×39mm",weight="約 3.85 kg",rng="有效 400m",
       cap="10 發固定彈倉、摺疊刺刀",mob="—",notes="56式半自動步槍（SKS 衍生），儀仗/民兵仍見。",
       tags=["步槍","舊式"],form_zh="半自動步槍（SKS）",wiki="Type 56 carbine"),
    mk("type-54-pistol","54式手槍","Type 54 pistol","Type 54","pistol","通用",cat="weapon",
       aliases=["54式","黑星"],caliber="7.62×25mm",weight="約 0.85 kg",rng="有效 50m",
       cap="8 發彈匣（TT-33 衍生）",mob="—",notes="54式手槍（蘇聯 TT-33 衍生），舊式仍有使用。",
       tags=["手槍","舊式"],form_zh="半自動手槍（TT 衍生）",wiki="Type 54 pistol"),
    mk("type-64-pistol","64式手槍","Type 64 pistol","Type 64","pistol","通用",cat="weapon",
       aliases=["64式"],caliber="7.62×17mm",weight="約 0.56 kg",rng="有效 50m",
       cap="7 發彈匣，軍警自衛",mob="—",notes="64式手槍，國產小型自衛手槍。",
       tags=["手槍"],form_zh="自衛手槍",wiki="Type 64 pistol"),
    mk("type-85-sniper","85式狙擊步槍","Type 85 sniper (SVD)","Type 85","dmr","通用",cat="weapon",
       aliases=["85式","79式","SVD 衍生"],caliber="7.62×54mmR",weight="約 4.4 kg",rng="有效 800m",
       cap="10 發彈匣、光學瞄準（SVD 衍生）",mob="—",notes="85式狙擊步槍（德拉貢諾夫 SVD 衍生）。",
       tags=["狙擊","SVD"],form_zh="半自動狙擊步槍（SVD）",wiki="Type 85 sniper rifle"),
    mk("w85-hmg","W85 12.7mm 高射機槍","W85 heavy MG","W85","hmg","通用",cat="weapon",
       aliases=["W85","QJC-88"],caliber="12.7×108mm",weight="約 18.5 kg（含三腳架）",rng="有效 1,500m",
       cap="彈鏈、對空/對地兩用、輕量化",mob="—",notes="W85／QJC-88 12.7mm 高射機槍，輕量化。",
       tags=["重機槍","高射"],form_zh="12.7mm 高射機槍",wiki="W85 heavy machine gun"),
    mk("pf-89","89式火箭筒","PF-89 rocket launcher","PF-89","at_rocket","通用",cat="weapon",
       aliases=["PF-89","89式火箭筒"],caliber="80mm 火箭",weight="發射器約 3.7 kg",rng="有效 400m",
       cap="一次性、破甲/多用途彈，穿深約 180mm",mob="單兵",notes="89式單兵火箭筒，一次性使用、班組反裝甲。",
       tags=["火箭筒","單兵"],form_zh="單兵火箭筒（80mm）",wiki="PF-89"),
    mk("fhj-84","84式雙管燃燒火箭筒","FHJ-84 incendiary launcher","FHJ-84","at_rocket","通用",cat="weapon",
       aliases=["FHJ-84"],caliber="62mm×2",weight="約 4 kg",rng="有效 250m",
       cap="燃燒/發煙火箭，清除工事/縱火/遮蔽",mob="單兵",notes="84式雙管燃燒火箭筒。",
       tags=["火箭筒","燃燒"],form_zh="雙管燃燒/發煙火箭筒",wiki="FHJ-84"),
    mk("qlb-06","06式半自動榴彈發射器","QLB-06 semi-auto GL","QLB-06","agl","通用",cat="weapon",
       aliases=["QLB-06"],caliber="35mm 榴彈",weight="約 9.1 kg",rng="有效 600m",
       cap="6 發彈鼓、單兵半自動",mob="單兵",notes="06式單兵半自動榴彈發射器。",
       tags=["榴彈發射器","單兵"],form_zh="單兵半自動榴彈發射器（35mm）",wiki="QLB-06"),
]

# ===== 批次 E1：海軍擴充 =====
NAVAL = [
    # --- 老式護衛艦 053 系列 ---
    mk("type-053h2g","053H2G型護衛艦（江衛I級）","Type 053H2G Jiangwei I","Type 053H2G","warship","海軍",
       aliases=["江衛I","Jiangwei I"],weight="滿載約 2,250 噸",length="112 m",crew="170",
       caliber="100mm 雙聯裝砲",cap="6×YJ-83 反艦、HQ-61 防空、2×3 魚雷",mob="護衛艦（FFG）",
       notes="江衛I級護衛艦，1990年代服役，反艦/防空/反潛。",tags=["護衛艦","江衛"],
       form_zh="飛彈護衛艦（江衛I級）",wiki="Type 053 frigate"),
    mk("type-053h1g","053H1G型護衛艦（江湖V級）","Type 053H1G Jianghu V","Type 053H1G","warship","海軍",
       aliases=["江湖V","Jianghu V"],weight="滿載約 1,900 噸",length="103 m",crew="200",
       caliber="2×100mm 砲",cap="8×YJ-83 反艦",mob="護衛艦（FF）",
       notes="江湖V級護衛艦，近岸巡邏/護漁執法常見。",tags=["護衛艦","江湖"],
       form_zh="飛彈護衛艦（江湖V級）",wiki="Type 053 frigate"),
    mk("type-053h","053H型護衛艦（江湖I級）","Type 053H Jianghu I","Type 053H","warship","海軍",
       aliases=["江湖I","Jianghu"],weight="滿載約 1,700 噸",length="103 m",crew="200",
       caliber="2×100mm 砲",cap="SY-1／YJ-8 反艦",mob="護衛艦（FF，多已除役/外援）",
       notes="江湖級護衛艦，早期主力，部分外援他國。",tags=["護衛艦","江湖"],
       form_zh="飛彈護衛艦（江湖I級）",wiki="Type 053 frigate"),
    # --- 獵潛艇 / 砲艇 ---
    mk("type-037","037型獵潛艇（海南級）","Type 037 Hainan-class","Type 037","patrol_boat","海軍",
       aliases=["海南級","Hainan"],weight="滿載約 430 噸",length="58.8 m",crew="70",
       caliber="4×57mm＋4×25mm",cap="反潛火箭深彈、深水炸彈",mob="近岸獵潛艇",
       notes="海南級獵潛艇，近岸反潛/巡邏，數量多。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-037is","037IS型獵潛艇（海青級）","Type 037IS Haiqing-class","Type 037IS","patrol_boat","海軍",
       aliases=["海青級","Haiqing"],weight="滿載約 478 噸",length="62.8 m",crew="71",
       caliber="2×2 37mm＋2×2 14.5mm",cap="反潛火箭深彈",mob="近岸獵潛艇",
       notes="海青級獵潛艇，037 改良反潛型。",tags=["獵潛艇","近岸"],
       form_zh="近岸獵潛艇（SC）",wiki="Hainan-class submarine chaser"),
    mk("type-062","062型砲艇（上海級）","Type 062 Shanghai-class","Type 062","patrol_boat","海軍",
       aliases=["上海級","Shanghai"],weight="滿載約 135 噸",length="38.8 m",crew="36",
       caliber="2×2 37mm＋2×2 25mm",cap="近岸巡邏/砲擊",mob="近岸砲艇",
       notes="上海級砲艇，近岸巡邏，產量極大、大量外援。",tags=["砲艇","近岸"],
       form_zh="近岸巡邏砲艇（PGB）",wiki="Shanghai-class gunboat"),
    mk("type-021","021型飛彈快艇（黃蜂級）","Type 021 Huangfeng-class","Type 021","patrol_boat","海軍",
       aliases=["黃蜂級","Huangfeng","Osa"],weight="滿載約 205 噸",length="38.6 m",crew="30",
       caliber="2×2 30mm",cap="4×SY-1／YJ-8 反艦飛彈",mob="飛彈快艇（PTG）",
       notes="黃蜂級飛彈快艇（蘇聯 Osa 衍生），舊式，逐步由 022 取代。",tags=["飛彈快艇"],
       form_zh="飛彈快艇（PTG）",wiki="Type 021-class missile boat"),
    # --- 掃雷/獵雷 ---
    mk("type-081","081型獵掃雷艦（渦藏級）","Type 081 Wozang-class","Type 081","minesweeper","海軍",
       aliases=["渦藏級","Wozang"],weight="滿載約 575 噸",length="55 m",crew="—",
       caliber="1×2 25mm",cap="獵雷聲納、遙控獵雷具",mob="獵掃雷艦（MHC）",
       notes="渦藏級獵掃雷艦，玻璃鋼艦體、遙控獵雷。",tags=["掃雷","獵雷"],
       form_zh="獵掃雷艦（MHC）",wiki="Type 081 minesweeper"),
    mk("type-082","082型掃雷艦（渦掃級）","Type 082 Wosao-class","Type 082","minesweeper","海軍",
       aliases=["渦掃級","Wosao"],weight="滿載約 400 噸",length="44.8 m",crew="—",
       caliber="2×2 25mm",cap="機械/電磁/聲掃雷具",mob="掃雷艦（MSC）",
       notes="渦掃級掃雷艦，近岸掃雷。",tags=["掃雷"],
       form_zh="掃雷艦（MSC）",wiki="Type 082 minesweeper"),
    # --- 兩棲 ---
    mk("type-073","073型登陸艦（玉登級）","Type 073 Yudeng-class","Type 073","amphibious_ship","海軍",
       aliases=["玉登級","Yudeng"],weight="滿載約 1,850 噸",length="87 m",crew="—",
       caliber="機砲",cap="約 500 噸裝載/戰車、兵員",mob="中型登陸艦（LSM）",
       notes="玉登級中型登陸艦。",tags=["登陸艦","兩棲"],
       form_zh="中型登陸艦（LSM）",wiki="Type 073 landing ship"),
    mk("type-074","074型登陸艦（玉北級）","Type 074 Yubei-class","Type 074","amphibious_ship","海軍",
       aliases=["玉北級","Yubei"],weight="滿載約 800 噸",length="58.4 m",crew="—",
       caliber="機砲",cap="裝甲車/兵員登陸",mob="通用登陸艇（LCU）",
       notes="玉北級通用登陸艇。",tags=["登陸艇","兩棲"],
       form_zh="通用登陸艇（LCU）",wiki="Type 074 landing ship"),
    # --- 潛艇 ---
    mk("type-032","032型潛艇（清級）","Type 032 Qing-class","Type 032","submarine","海軍",cat="vehicle",
       aliases=["清級","Qing"],weight="水下約 6,628 噸",length="92.6 m",crew="88",
       caliber="魚雷/飛彈試射",cap="潛射彈道/巡航飛彈試驗平台（JL-2／JL-3 試射）",mob="常規動力試驗潛艇",
       notes="清級試驗潛艇，全球最大常規潛艇之一，用於潛射飛彈試驗。",tags=["潛艇","試驗"],
       form_zh="試驗潛艇（SSB test）",wiki="Type 032 submarine"),
    mk("type-039c","039C型潛艇（元級改）","Type 039C Yuan-class","Type 039C","submarine","海軍",cat="vehicle",
       aliases=["元級改","Yuan"],weight="水下約 3,600 噸",length="77.6 m",crew="—",
       caliber="533mm 魚雷",cap="YJ-18/YJ-82 潛射反艦、AIP 不依賴空氣推進",mob="常規動力攻擊潛艇（SSK/AIP）",
       notes="元級最新改型，具匿蹤外形與 AIP。",tags=["潛艇","AIP"],
       form_zh="常規攻擊潛艇（AIP）",wiki="Type 039A submarine"),
    mk("type-092","092型戰略核潛艇（夏級）","Type 092 Xia-class","Type 092","submarine","海軍",cat="vehicle",
       aliases=["夏級","Xia"],weight="水下約 8,000 噸",length="120 m",crew="140",
       caliber="彈道飛彈",cap="12×JL-1 潛射彈道飛彈",mob="彈道飛彈核潛艇（SSBN）",
       notes="夏級，中國第一代戰略核潛艇（1艘）。",tags=["核潛艇","SSBN"],
       form_zh="彈道飛彈核潛艇（SSBN）",wiki="Type 092 submarine"),
    mk("type-096","096型戰略核潛艇（唐級，研發中）","Type 096 Tang-class","Type 096","submarine","海軍",cat="vehicle",
       aliases=["唐級","Tang"],weight="—",length="—",crew="—",
       caliber="彈道飛彈",cap="JL-3 潛射洲際彈道飛彈（推測）",mob="次世代彈道飛彈核潛艇（SSBN，研發中）",
       notes="唐級次世代 SSBN，發展中，諸元為外界推測。",tags=["核潛艇","SSBN","研發中"],
       form_zh="次世代彈道飛彈核潛艇（SSBN）",wiki="Type 096 submarine"),
    mk("type-033","033型潛艇（羅密歐級）","Type 033 Romeo-class","Type 033","submarine","海軍",cat="vehicle",
       aliases=["羅密歐級","Romeo"],weight="水下約 1,712 噸",length="76.6 m",crew="54",
       caliber="533mm 魚雷",cap="魚雷/水雷（舊式，多除役/訓練）",mob="常規動力潛艇（舊式）",
       notes="羅密歐級（蘇聯衍生），舊式，多已退役或訓練用。",tags=["潛艇","舊式"],
       form_zh="常規潛艇（舊式）",wiki="Type 033 submarine"),
    # --- 補給/輔助/特種艦 ---
    mk("type-904","904型補給艦（大運級）","Type 904 Dayun-class","Type 904","replenishment","海軍",
       aliases=["大運級","Dayun"],weight="滿載約 15,000 噸",length="156 m",crew="—",
       caliber="機砲",cap="島礁補給、乾貨/物資運輸",mob="島礁補給艦（AKS）",
       notes="大運級島礁補給艦，南海島礁後勤。",tags=["補給艦","後勤"],
       form_zh="島礁補給艦（AKS）",wiki="Type 904 replenishment ship"),
    mk("type-905","905型補給艦（福清級）","Type 905 Fuqing-class","Type 905","replenishment","海軍",
       aliases=["福清級","Fuqing"],weight="滿載約 21,750 噸",length="168.2 m",crew="130",
       caliber="機砲",cap="燃油/彈藥/乾貨橫向補給",mob="遠洋綜合補給艦（AOR，舊式）",
       notes="福清級綜合補給艦，第一代遠洋補給艦。",tags=["補給艦","AOR"],
       form_zh="綜合補給艦（AOR）",wiki="Fuqing-class tanker"),
    mk("type-926","926型潛艇支援艦（大江級）","Type 926 Dajiang-class","Type 926","auxiliary","海軍",
       aliases=["大江級","Dajiang"],weight="滿載約 9,500 噸",length="156 m",crew="—",
       caliber="機砲",cap="搭載 LR-7 深潛救生艇、潛艇救援",mob="潛艇支援/救援艦（ASR）",
       notes="大江級潛艇支援艦，搭載深潛救生艇。",tags=["潛艇救援","支援艦"],
       form_zh="潛艇支援救援艦（ASR）",wiki="Type 926 submarine support ship"),
    mk("type-920","920型醫院船（和平方舟）","Type 920 Anwei-class (Peace Ark)","Type 920","hospital_ship","海軍",
       aliases=["和平方舟","Peace Ark","岱山島"],weight="滿載約 14,000 噸",length="178 m",crew="醫護 428",
       caliber="—",cap="300 床位、手術室、遠海醫療/人道救援",mob="醫院船（AH）",
       notes="和平方舟醫院船，遠海醫療與人道任務，多次出訪。",tags=["醫院船","人道"],
       form_zh="醫院船（AH）",wiki="Chinese hospital ship Peace Ark"),
    mk("yuanwang","遠望號測量船（航天測控）","Yuanwang tracking ship","Yuanwang","survey_ship","海軍",
       aliases=["遠望","Yuanwang"],weight="滿載約 25,000 噸",length="222 m",crew="—",
       caliber="—",cap="航天測控天線、飛彈/衛星彈道測量",mob="航天遠洋測量船",
       notes="遠望系列航天測量船，支援衛星/飛彈測控。",tags=["測量船","航天測控"],
       form_zh="航天遠洋測量船",wiki="Yuanwang"),
    mk("type-636a","636A型測量船","Type 636A survey ship","Type 636A","survey_ship","海軍",
       aliases=["636A"],weight="滿載約 5,900 噸",length="129.3 m",crew="—",
       caliber="—",cap="海洋/水文調查、聲納測繪",mob="海洋測量船（AGS）",
       notes="636A 海洋綜合調查測量船。",tags=["測量船","海洋調查"],
       form_zh="海洋測量船（AGS）",wiki="Type 636A survey ship"),
    # --- 海警（海上執法）---
    mk("type-818","818型海警船（昭頭級）","Type 818 Zhaotou-class CCG cutter","Type 818","coast_guard","海警",
       aliases=["昭頭級","Zhaotou","海警2901","海警3901"],weight="滿載約 12,000 噸",length="165 m",crew="—",
       caliber="76mm 主砲＋副砲",cap="世界最大海警執法船（基於 054A 技術）",mob="大型海警執法船",
       notes="昭頭級海警船，滿載萬噸，世界最大海上執法船。",tags=["海警","執法"],
       form_zh="大型海警巡防船（CG cutter）",wiki="Zhaotou-class patrol vessel"),
    mk("type-718b","718B型海警船","Type 718B CCG cutter","Type 718B","coast_guard","海警",
       aliases=["718B"],weight="滿載約 4,000 噸",length="—",crew="—",
       caliber="76mm 主砲",cap="遠海維權執法巡邏",mob="海警巡防船",
       notes="718B 型海警巡防船。",tags=["海警","執法"],
       form_zh="海警巡防船（CG cutter）",wiki="China Coast Guard"),
]

# ===== 批次 E2：空軍／陸航擴充（直升機、老式機、無人機、特種機）=====
AIR = [
    mk("z-8g","直-8G 通用運輸直升機","Z-8G transport helicopter","Z-8G","helicopter","陸軍",
       aliases=["直8G"],weight="最大起飛約 13,000 kg",crew="機組 3＋27 兵",rng="航程約 800 km",
       cap="運兵/物資、可吊掛",mob="中型運輸直升機",notes="直-8 系列通用運輸直升機。",
       tags=["直升機","運輸"],form_zh="中型運輸直升機",wiki="Harbin Z-8"),
    mk("z-8l","直-8L 大型運輸直升機","Z-8L heavy transport helicopter","Z-8L","helicopter","陸軍",
       aliases=["直8L"],weight="最大起飛約 15,000 kg",crew="機組＋大量兵員",rng="航程約 900 km",
       cap="加寬機身、可載輕型車輛",mob="大型運輸直升機",notes="直-8 加寬機身重型運輸型。",
       tags=["直升機","運輸"],form_zh="大型運輸直升機",wiki="Harbin Z-8"),
    mk("z-9w","直-9W 武裝直升機","Z-9W armed helicopter","Z-9W","helicopter_attack","陸軍",
       aliases=["直9W"],weight="最大起飛約 4,100 kg",crew="2",rng="航程約 1,000 km",
       cap="HJ-8 反戰車飛彈、火箭、機砲",mob="輕型武裝直升機",notes="直-9 武裝偵察/攻擊型（海豚衍生）。",
       tags=["直升機","武裝"],form_zh="輕型武裝直升機",wiki="Harbin Z-9"),
    mk("z-19e","直-19E 偵察攻擊直升機","Z-19E scout/attack helicopter","Z-19E","helicopter_attack","陸軍",
       aliases=["直19E"],weight="最大起飛約 4,500 kg",crew="2",rng="航程約 700 km",
       cap="天燕-90 空對空、反戰車飛彈、火箭",mob="偵察/攻擊直升機",notes="直-19 出口/改良型，串列雙座。",
       tags=["直升機","偵攻"],form_zh="偵察攻擊直升機",wiki="Harbin Z-19"),
    mk("z-11wb","直-11WB 武裝偵察直升機","Z-11WB armed scout","Z-11WB","helicopter_attack","陸軍",
       aliases=["直11WB"],weight="最大起飛約 2,200 kg",crew="2",rng="航程約 600 km",
       cap="輕型反戰車飛彈、機槍、火箭",mob="輕型武裝偵察直升機",notes="直-11 武裝偵察型。",
       tags=["直升機","武裝"],form_zh="輕型武裝偵察直升機",wiki="Changhe Z-11"),
    mk("mi-171","米-171 中型運輸直升機","Mil Mi-171","Mi-171","helicopter","陸軍",
       aliases=["Mi-171","米171"],weight="最大起飛約 13,000 kg",crew="機組 3＋24 兵",rng="航程約 590 km",
       cap="運兵/物資、可外掛武器",mob="中型運輸直升機（俄製）",notes="米-171 中型運輸直升機，陸航主力運輸機隊。",
       tags=["直升機","運輸","俄製"],form_zh="中型運輸直升機",wiki="Mil Mi-8"),
    mk("z-15","直-15 中型多用途直升機","Z-15 (AC352)","Z-15","helicopter","陸軍",
       aliases=["AC352","直15"],weight="最大起飛約 7,500 kg",crew="機組＋14 兵",rng="航程約 850 km",
       cap="運輸/搜救/多用途",mob="中型多用途直升機",notes="直-15／AC352 中型直升機（與空巴 H175 同源）。",
       tags=["直升機","多用途"],form_zh="中型多用途直升機",wiki="Airbus Helicopters H175"),
    # 老式作戰機
    mk("q-5","強-5 攻擊機","Nanchang Q-5","Q-5","aircraft_strike","空軍",
       aliases=["強5","A-5","Fantan"],weight="最大起飛約 12,000 kg",crew="1",rng="作戰半徑約 400 km",
       caliber="2×23mm 機砲",cap="炸彈/火箭/近距空對空，載彈約 2,000 kg",mob="Mach 1.12；2×渦噴-6",
       notes="強-5 對地攻擊機（MiG-19 衍生），已大量退役。",tags=["攻擊機","舊式"],
       form_zh="對地攻擊機",wiki="Nanchang Q-5"),
    mk("j-7e","殲-7E／G 戰鬥機","Chengdu J-7E/G","J-7E","aircraft_fighter","空軍",
       aliases=["殲7E","殲7G","J-7G"],weight="最大起飛約 9,100 kg",crew="1",rng="作戰半徑約 600 km",
       caliber="2×30mm",cap="PL-5／PL-8 近距空對空、火箭/炸彈",mob="Mach 2；渦噴-13（雙三角翼改良）",
       notes="殲-7 後期改良型（雙三角翼、改良航電），逐步退役。",tags=["戰鬥機","舊式"],
       form_zh="輕型戰鬥機（殲-7 後期型）",wiki="Chengdu J-7"),
    mk("j-8b","殲-8B 攔截機","Shenyang J-8B","J-8B","aircraft_fighter","空軍",
       aliases=["殲8B"],weight="最大起飛約 17,800 kg",crew="1",rng="作戰半徑約 800 km",
       caliber="23mm 機砲",cap="PL-5／PL-8／PL-11、火箭",mob="Mach 2.2；2×渦噴-13",
       notes="殲-8B 全天候攔截機，逐步退役/改偵察電戰。",tags=["攔截機","舊式"],
       form_zh="攔截戰鬥機（殲-8B）",wiki="Shenyang J-8"),
    # 無人機
    mk("ch-3","彩虹-3 察打無人機","CASC CH-3","CH-3","uav","空軍",
       aliases=["彩虹3","CH-3"],weight="最大起飛約 640 kg",crew="無人",rng="航程約 2,400 km／滯空 12h",
       cap="AR-1 反戰車飛彈、FT 系列導引炸彈",mob="中空長航時；螺旋槳",
       notes="彩虹-3 察打一體無人機，外銷多國。",tags=["無人機","察打"],
       form_zh="察打一體無人機（彩虹-3）",wiki="CASC Rainbow"),
    mk("wing-loong-10","翼龍-10 高空長航時無人機","Wing Loong-10 (Cloud Shadow)","WL-10","uav","空軍",
       aliases=["雲影","Cloud Shadow","WZ-10 UAV"],weight="最大起飛約 3,200 kg",crew="無人",
       rng="航程約 4,000 km／升限 14,000 m",cap="偵察/電子情報/精確打擊",mob="噴射動力、高空高速",
       notes="翼龍-10（雲影）噴射高空無人機。",tags=["無人機","高空"],
       form_zh="高空長航時無人機（翼龍-10）",wiki="Wing Loong 10"),
    mk("wz-5","無偵-5 高空偵察無人機（舊式）","WZ-5 recon drone","WZ-5","uav","空軍",
       aliases=["無偵5","Chang Hong"],weight="—",crew="無人",rng="—",
       cap="高空照相偵察（舊式）",mob="早期噴射偵察無人機",notes="無偵-5 早期高空偵察無人機（長虹），歷史型。",
       tags=["無人機","偵察","舊式"],form_zh="高空偵察無人機（舊式）",wiki="Chengdu WZ-5"),
    mk("asn-206","ASN-206 戰術無人機","ASN-206 tactical UAV","ASN-206","uav","陸軍",
       aliases=["ASN-206"],weight="最大起飛約 222 kg",crew="無人",rng="航程約 150 km／滯空 8h",
       cap="戰場偵察/砲兵校射/電子偵察",mob="活塞螺旋槳、彈射起飛",notes="ASN-206 戰術偵察無人機（西工大）。",
       tags=["無人機","戰術偵察"],form_zh="戰術偵察無人機（ASN-206）",wiki="ASN-206"),
    # 特種任務機
    mk("y-8g","運-8G 電子戰機","Y-8G ECM aircraft","Y-8G","aircraft_recon","空軍",
       aliases=["運8G","GX-4"],weight="—",crew="—",rng="—",cap="電子干擾/壓制（高新4號）",
       mob="Y-8 平台特種機",notes="運-8G 電子戰/干擾機（高新工程）。",tags=["電子戰","特種機"],
       form_zh="電子戰機（Y-8 平台）",wiki="Shaanxi Y-8"),
    mk("y-9g","運-9G 電子戰機","Y-9G ECM aircraft","Y-9G","aircraft_recon","空軍",
       aliases=["運9G","高新12"],weight="—",crew="—",rng="航程約 5,000 km",cap="電子偵察/干擾",
       mob="Y-9 平台特種機",notes="運-9G 電子戰機（高新工程）。",tags=["電子戰","特種機"],
       form_zh="電子戰機（Y-9 平台）",wiki="Shaanxi Y-9"),
    mk("kj-500a","空警-500A 預警機","KJ-500A AEW&C","KJ-500A","aircraft_aew","空軍",
       aliases=["空警500A"],weight="MTOW 約 77 噸",crew="多名操作員",rng="滯空約 12h",
       cap="三面 AESA（360°）＋空中受油",mob="Y-9 平台預警機",notes="空警-500A，加裝空中受油探管的改良型。",
       tags=["預警機","AEW"],form_zh="空中預警管制機（KJ-500A）",wiki="KJ-500"),
]

# ===== 批次 E3：陸軍擴充（老式坦克、輪式裝甲、火砲、工兵/搶救/架橋）=====
GROUND = [
    mk("type-59","59式中型坦克","Type 59 MBT","Type 59","mbt","陸軍",
       aliases=["59式","WZ120"],weight="約 36 噸",crew="4",caliber="100mm 線膛砲",
       rng="公路 50 km/h",mob="12150L V12 520hp",armor="鑄造均質裝甲",
       cap="蘇聯 T-54A 衍生，中國第一代主戰坦克",notes="59式中型坦克，產量極大，衍生眾多，部分仍後備/訓練。",
       tags=["坦克","舊式"],form_zh="中型坦克（T-54A 衍生）",wiki="Type 59 tank"),
    mk("type-59d","59D式主戰坦克","Type 59D MBT","Type 59D","mbt","陸軍",
       aliases=["59D式"],weight="約 39 噸",crew="4",caliber="105mm 線膛砲（可射砲射飛彈）",
       rng="公路 50 km/h",mob="580hp 柴油",armor="複合＋爆炸反應裝甲",
       cap="105mm 砲、火控升級、砲射飛彈",notes="59式深度現代化型，換 105mm 砲與 ERA。",
       tags=["坦克"],form_zh="主戰坦克（59 現代化）",wiki="Type 59 tank"),
    mk("type-69","69式主戰坦克","Type 69 MBT","Type 69","mbt","陸軍",
       aliases=["69式","WZ121"],weight="約 36.5 噸",crew="4",caliber="100mm 滑膛砲",
       rng="公路 50 km/h",mob="12150L-7 580hp",armor="鑄造裝甲",
       cap="59 式改良，大量外銷（兩伊戰爭）",notes="69式主戰坦克，外銷量大，國內多退役。",
       tags=["坦克","舊式"],form_zh="主戰坦克（69 式）",wiki="Type 69 tank"),
    mk("type-79","79式主戰坦克","Type 79 MBT","Type 79","mbt","陸軍",
       aliases=["79式"],weight="約 37.5 噸",crew="4",caliber="105mm 線膛砲",
       rng="公路 50 km/h",mob="580hp 柴油",armor="鑄造＋複合",
       cap="首用 105mm 線膛砲與火控",notes="79式主戰坦克，69 改良、引進西方 105mm 砲技術。",
       tags=["坦克","舊式"],form_zh="主戰坦克（79 式）",wiki="Type 79 tank"),
    mk("type-80","80式主戰坦克","Type 80 MBT","Type 80","mbt","陸軍",
       aliases=["80式","ZTZ-80"],weight="約 38 噸",crew="4",caliber="105mm 線膛砲",
       rng="公路 60 km/h",mob="730hp 柴油",armor="複合裝甲",
       cap="新底盤（六對負重輪）、現代火控",notes="80式主戰坦克，第二代國產坦克起點，衍生 88/96 式。",
       tags=["坦克"],form_zh="主戰坦克（80 式）",wiki="Type 80 tank"),
    mk("ptl-02","PTL-02 輪式突擊砲","PTL-02 assault gun","PTL-02","assault_gun","陸軍",
       aliases=["PTL02","100mm 輪突"],weight="約 19 噸",crew="4",caliber="100mm 線膛砲",
       rng="公路 85 km/h",mob="6×6 輪式",armor="防輕武器/破片",
       cap="100mm 砲、反裝甲/火力支援",notes="PTL-02 輪式突擊砲（WMZ551 底盤），快速反應部隊。",
       tags=["突擊砲","輪式"],form_zh="輪式突擊砲（100mm）",wiki="PTL02"),
    mk("wz-523","WZ-523 輪式裝甲運兵車","WZ-523 APC","WZ-523","apc_wheeled","陸軍",
       aliases=["WZ523"],weight="約 11.5 噸",crew="2＋10 兵",caliber="12.7mm 機槍",
       rng="公路 80 km/h",mob="6×6 兩棲",armor="鋼裝甲防輕武器",
       cap="運兵/維穩/兩棲",notes="WZ-523 輪式裝甲運兵車，亦供武警維穩。",
       tags=["裝甲車","輪式"],form_zh="輪式裝甲運兵車（APC）",wiki="WZ523"),
    mk("plz-45","PLZ-45 155mm 自走榴彈砲","PLZ-45 SPH","PLZ-45","sph","陸軍",
       aliases=["PLZ45"],weight="約 33 噸",crew="5",caliber="155mm/45 倍徑",
       rng="射程 39 km（底排增程）",mob="履帶自走",armor="鋼裝甲",
       cap="外銷主力（科威特、沙烏地等）",notes="PLZ-45 外銷型 155mm 自走砲，成套彈藥/指揮系統。",
       tags=["自走砲","外銷"],form_zh="自走榴彈砲（155mm，外銷）",wiki="PLZ-45"),
    mk("plz-52","PLZ-52 155mm 自走榴彈砲","PLZ-52 SPH","PLZ-52","sph","陸軍",
       aliases=["PLZ52"],weight="約 43 噸",crew="5",caliber="155mm/52 倍徑",
       rng="射程 53 km（火箭增程）",mob="履帶自走",armor="鋼裝甲",
       cap="PLZ-05 外銷升級版",notes="PLZ-52 為 PLZ-05 的 52 倍徑外銷升級型，射程更遠。",
       tags=["自走砲","外銷"],form_zh="自走榴彈砲（155mm/52）",wiki="PLZ-52"),
    mk("sh-15","SH-15 155mm 車載榴彈砲","SH-15 truck howitzer","SH-15","truck_howitzer","陸軍",
       aliases=["SH15","PCL-181 外銷"],weight="約 22 噸",crew="6",caliber="155mm/52 倍徑",
       rng="射程 20 km（一般）/53 km（增程）",mob="6×6 卡車底盤",armor="裝甲駕駛室",
       cap="PCL-181 的外銷型（巴基斯坦等）",notes="SH-15 車載榴彈砲，PCL-181 外銷版本。",
       tags=["車載砲","外銷"],form_zh="車載榴彈砲（155mm）",wiki="SH-15"),
    mk("phl-11","PHL-11 122mm 火箭砲","PHL-11 MLRS","PHL-11","mlrs","陸軍",
       aliases=["PHL11","Type 11"],weight="約 22 噸",crew="—",caliber="122mm×40 管",
       rng="射程 20–40 km",mob="6×6 車載、模組化裝填",armor="裝甲駕駛室",
       cap="40 聯裝 122mm、模組快速再裝填",notes="PHL-11 模組化 122mm 火箭砲。",
       tags=["火箭砲","122mm"],form_zh="122mm 多管火箭砲",wiki="PHL-11"),
    mk("gsl-131","GSL-131 掃雷破障車","GSL-131 mine-clearing vehicle","GSL-131","engineer","陸軍",
       aliases=["GSL131"],weight="約 30 噸",crew="2",caliber="—",
       rng="—",mob="履帶（99/96 底盤）",armor="裝甲",
       cap="掃雷犁/爆破掃雷索、開闢通路",notes="GSL-131 裝甲掃雷破障車，為裝甲部隊開路。",
       tags=["工兵","掃雷"],form_zh="裝甲掃雷破障車",wiki="GSL-131"),
    mk("gcz-112","GCZ-112 裝甲工程車","GCZ-112 combat engineer vehicle","GCZ-112","engineer","陸軍",
       aliases=["GCZ112"],weight="約 38 噸",crew="3",caliber="12.7mm 機槍",
       rng="—",mob="履帶裝甲底盤",armor="裝甲",
       cap="推土鏟/挖掘臂/絞盤，構工/清障",notes="GCZ-112 裝甲工程車，戰場構工與清障。",
       tags=["工兵","構工"],form_zh="裝甲工程車（CEV）",wiki="GCZ-112"),
    mk("type-84-bridge","84式架橋坦克","Type 84 bridgelayer","Type 84","bridge","陸軍",
       aliases=["84式架橋","HJJ-84"],weight="約 38 噸",crew="3",caliber="—",
       rng="—",mob="69/79 坦克底盤",armor="裝甲",
       cap="剪刀式車轍橋、跨距約 18 m",notes="84式架橋坦克，快速架設車轍橋供裝甲通過。",
       tags=["工兵","架橋"],form_zh="架橋坦克（AVLB）",wiki="Type 84 bridgelayer"),
    mk("type-654-arv","654式裝甲搶救車","Type 654 ARV","Type 654","recovery","陸軍",
       aliases=["654式","搶救車"],weight="約 38 噸",crew="4",caliber="12.7mm 機槍",
       rng="—",mob="履帶裝甲底盤",armor="裝甲",
       cap="絞盤/吊臂/推土鏟，戰場搶修拖救",notes="654 式裝甲搶救車，拖救與野戰搶修受損戰車。",
       tags=["工兵","搶救"],form_zh="裝甲搶救車（ARV）",wiki="Type 654 armoured recovery vehicle"),
]

# ===== 批次 E7：海軍（更多老艦/快艇/試驗艦）=====
NAVAL2 = [
    mk("type-051","051型驅逐艦（旅大級）","Type 051 Luda-class","Type 051","warship","海軍",
       aliases=["旅大級","Luda"],weight="滿載約 3,670 噸",length="132 m",crew="280",
       caliber="2×2 130mm 砲",cap="HY-2／YJ-8 反艦、深彈；第一代國產驅逐艦",mob="驅逐艦（DDG，多退役）",
       notes="旅大級驅逐艦，中國第一代國產驅逐艦，大多退役。",tags=["驅逐艦","舊式"],
       form_zh="飛彈驅逐艦（旅大級）",wiki="Type 051 destroyer"),
    mk("type-053h1","053H1型護衛艦（江湖II級）","Type 053H1 Jianghu II","Type 053H1","warship","海軍",
       aliases=["江湖II","Jianghu II"],weight="滿載約 1,700 噸",length="103 m",crew="200",
       caliber="2×2 100mm 砲",cap="SY-1／YJ-8 反艦",mob="護衛艦（FF）",
       notes="江湖II級護衛艦。",tags=["護衛艦","江湖"],form_zh="飛彈護衛艦（江湖II級）",wiki="Type 053 frigate"),
    mk("type-037ii","037II型飛彈艇（紅箭級）","Type 037II Houjian-class","Type 037II","patrol_boat","海軍",
       aliases=["紅箭級","Houjian"],weight="滿載約 520 噸",length="65.4 m",crew="75",
       caliber="1×2 37mm＋2×2 30mm",cap="6×YJ-8 反艦飛彈",mob="飛彈艇（PGG）",
       notes="紅箭級飛彈艇，037 衍生飛彈艇。",tags=["飛彈艇","近岸"],form_zh="飛彈艇（PGG）",wiki="Houjian-class missile boat"),
    mk("type-024","024型飛彈艇（河谷級）","Type 024 Hegu-class","Type 024","patrol_boat","海軍",
       aliases=["河谷級","Hegu"],weight="滿載約 68 噸",length="27 m",crew="17",
       caliber="1×2 25mm",cap="2×SY-1 反艦飛彈",mob="小型飛彈艇（舊式）",
       notes="河谷級小型飛彈艇（Komar 衍生），舊式。",tags=["飛彈艇","舊式"],form_zh="小型飛彈艇（舊式）",wiki="Type 024 missile boat"),
    mk("type-909","909型試驗艦（畢昇級）","Type 909 Bisheng-class trials ship","Type 909","auxiliary","海軍",
       aliases=["畢昇級","Bisheng"],weight="滿載約 6,000 噸",length="130 m",crew="—",
       caliber="測試武器",cap="新型艦載武器/雷達海上測試平台",mob="武器測試艦",
       notes="909／909A 型武器測試艦，新裝備海試平台。",tags=["試驗艦","測試"],form_zh="武器測試艦",wiki="Type 909 experimental ship"),
    mk("type-925","925型潛艇支援艦（大峰級）","Type 925 Dafeng-class ASR","Type 925","auxiliary","海軍",
       aliases=["大峰級","Dafeng"],weight="滿載約 4,200 噸",length="112.5 m",crew="—",
       caliber="機砲",cap="潛艇救援/支援、援潛鐘",mob="潛艇支援救援艦（ASR，舊式）",
       notes="大峰級潛艇支援艦。",tags=["潛艇救援","支援艦"],form_zh="潛艇支援救援艦（ASR）",wiki="Type 925 submarine support ship"),
    mk("type-072iii","072III型登陸艦（玉亭II級）","Type 072III Yuting II","Type 072III","amphibious_ship","海軍",
       aliases=["玉亭II","Yuting II"],weight="滿載約 4,800 噸",length="119.5 m",crew="104",
       caliber="機砲",cap="約 250 兵/10 戰車、直升機甲板",mob="大型登陸艦（LST）",
       notes="玉亭II級戰車登陸艦。",tags=["登陸艦","兩棲"],form_zh="戰車登陸艦（LST）",wiki="Type 072 landing ship"),
    mk("type-095","095型攻擊核潛艇（研發中）","Type 095 SSN","Type 095","submarine","海軍",cat="vehicle",
       aliases=["095型","Sui-class?"],weight="—",length="—",crew="—",
       caliber="533mm 魚雷／垂發",cap="魚雷、YJ-18、可能垂直發射（推測）",mob="次世代攻擊核潛艇（SSN，研發中）",
       notes="095 型次世代攻擊核潛艇，發展中，諸元為外界推測。",tags=["核潛艇","SSN","研發中"],
       form_zh="次世代攻擊核潛艇（SSN）",wiki="Type 095 submarine"),
    mk("type-039b","039B型潛艇（元級）","Type 039B Yuan-class","Type 039B","submarine","海軍",cat="vehicle",
       aliases=["元級","Yuan B"],weight="水下約 3,600 噸",length="77.6 m",crew="—",
       caliber="533mm 魚雷",cap="YJ-18 潛射反艦、AIP",mob="常規動力攻擊潛艇（AIP）",
       notes="元級 039B 改進型，AIP 常規潛艇。",tags=["潛艇","AIP"],form_zh="常規攻擊潛艇（AIP）",wiki="Type 039A submarine"),
]

# ===== 批次 E8：空軍（更多機型/教練/加油/預警/進口）=====
AIR2 = [
    mk("jl-9","教練-9 山鷹高級教練機","Guizhou JL-9 Mountain Eagle","JL-9","aircraft_trainer","空軍",
       aliases=["JL-9","山鷹","FTC-2000"],weight="MTOW 約 9,800 kg",crew="2",rng="航程約 2,400 km",
       caliber="23mm 機砲（選配）",cap="教練/輕攻擊，可掛 PL-5/火箭",mob="Mach 1.05；渦噴-13",
       notes="教練-9 山鷹高級教練機，殲-7/8 飛行員養成。",tags=["教練機"],form_zh="高級教練機（山鷹）",wiki="Guizhou JL-9"),
    mk("kj-200","空警-200 預警機（平衡木）","KJ-200 AEW&C","KJ-200","aircraft_aew","空軍",
       aliases=["KJ-200","平衡木","高新5"],weight="Y-8 平台",crew="多名操作員",rng="滯空約 7–8h",
       cap="平衡木式雙側 AESA 天線",mob="Y-8/Y-9 平台預警機",sensors="平衡木相位陣列雷達",
       notes="空警-200 戰術預警機，平衡木天線。",tags=["預警機","AEW"],form_zh="空中預警管制機（平衡木）",wiki="KJ-200"),
    mk("h-6d","轟-6D 海軍轟炸機","Xian H-6D","H-6D","aircraft_bomber","空軍",branch_hint="海軍",
       aliases=["轟6D","H-6D"],weight="—",crew="4",rng="作戰半徑約 1,800 km",
       caliber="機砲",cap="2×YJ-6／C-601 反艦飛彈",mob="渦噴，海軍反艦轟炸機",
       notes="轟-6D 海軍反艦轟炸機（舊式），海航使用。",tags=["轟炸機","反艦","舊式"],form_zh="海軍反艦轟炸機（H-6D）",wiki="Xian H-6"),
    mk("hy-6","轟油-6 空中加油機","Xian HY-6 tanker","HY-6","aircraft_tanker","空軍",
       aliases=["轟油6","HY-6","H-6U"],weight="—",crew="—",rng="—",
       caliber="—",cap="軟管加油、可為 J-8/J-10 空中加油",mob="H-6 平台加油機",
       notes="轟油-6 空中加油機，H-6 改裝軟管加油。",tags=["加油機"],form_zh="空中加油機（H-6 平台）",wiki="Xian H-6"),
    mk("su-27sk","蘇-27SK 戰鬥機（進口基型）","Sukhoi Su-27SK","Su-27SK","aircraft_fighter","空軍",
       aliases=["Su-27SK","蘇27"],weight="MTOW 約 30,000 kg",crew="1",rng="作戰半徑約 1,500 km",
       caliber="30mm 機砲",cap="R-27／R-73 空對空，10 掛點",mob="Mach 2.35；2×AL-31F",
       notes="蘇-27SK 進口基型空優戰機，衍生殲-11。",tags=["戰鬥機","進口"],form_zh="空優戰鬥機（Su-27SK）",wiki="Sukhoi Su-27"),
    mk("j-10s","殲-10S 雙座型","Chengdu J-10S","J-10S","aircraft_fighter","空軍",
       aliases=["殲10S","J-10AS"],weight="—",crew="2",rng="作戰半徑約 1,200 km",
       caliber="23mm 機砲",cap="PL-8／PL-12，教練/作戰雙用",mob="Mach 1.8；AL-31FN/WS-10",
       notes="殲-10 雙座型，教練兼作戰。",tags=["戰鬥機","雙座"],form_zh="雙座多用途戰機（殲-10S）",wiki="Chengdu J-10"),
    mk("y-12","運-12 輕型運輸機","Harbin Y-12","Y-12","aircraft_transport","空軍",
       aliases=["運12","Y-12"],weight="MTOW 約 5,700 kg",crew="2",rng="航程約 1,340 km",
       caliber="—",cap="17 座/貨運、短場起降",mob="雙渦槳輕型運輸機",
       notes="運-12 輕型多用途運輸機，聯絡/運輸/傘訓。",tags=["運輸機","輕型"],form_zh="輕型運輸機（運-12）",wiki="Harbin Y-12"),
    mk("ch-6","彩虹-6 高空長航時無人機","CASC CH-6","CH-6","uav","空軍",
       aliases=["彩虹6","CH-6"],weight="MTOW 約 7,800 kg",crew="無人",rng="滯空約 20h",
       cap="偵察/察打、可掛多枚武器",mob="噴射/渦槳、高空長航時",
       notes="彩虹-6 大型高空長航時察打/偵察無人機。",tags=["無人機","高空"],form_zh="高空長航時無人機（彩虹-6）",wiki="CASC Rainbow"),
]

# ===== 批次 E9：陸軍（高砲、老式裝甲、自行迫榴）=====
GROUND2 = [
    mk("type-63-apc","63式裝甲輸送車（YW531）","Type 63 APC (YW531)","Type 63","apc_tracked","陸軍",
       aliases=["63式裝甲車","YW531"],weight="約 12.6 噸",crew="2＋13 兵",caliber="12.7mm 機槍",
       rng="公路 65 km/h",mob="履帶兩棲",armor="鋼裝甲防輕武器",cap="運兵/兩棲、衍生眾多",
       notes="63式履帶裝甲輸送車，中國第一代國產 APC，衍生廣。",tags=["裝甲車","履帶","舊式"],
       form_zh="履帶裝甲輸送車（APC）",wiki="Type 63 armoured personnel carrier"),
    mk("pgz-88","88式自行高射砲","Type 88 SPAAG","Type 88","spaag","陸軍",
       aliases=["88式自高","PGZ-88"],weight="約 30 噸",crew="4",caliber="2×37mm",
       rng="有效 3,500m",mob="履帶（69 底盤）",armor="裝甲",cap="雙 37mm、雷達/光電火控",
       notes="88式自行高射砲，雙 37mm 對空。",tags=["自行高砲","舊式"],form_zh="自行高射砲（雙37mm）",wiki="Type 88 self-propelled anti-aircraft gun"),
    mk("type-65-aaa","65式 37mm 高射砲","Type 65 37mm AAA","Type 65","spaag","陸軍",
       aliases=["65式高砲"],weight="牽引約 2.8 噸",crew="8",caliber="2×37mm",
       rng="有效 3,500m",mob="牽引式",armor="—",cap="雙管 37mm 對空/對地",
       notes="65式雙 37mm 牽引高射砲，近岸/野戰防空。",tags=["高射砲","牽引","舊式"],form_zh="牽引式高射砲（雙37mm）",wiki="Type 65 anti-aircraft gun"),
    mk("type-74-aaa","74式雙 37mm 高射砲","Type 74 37mm AAA","Type 74","spaag","陸軍",
       aliases=["74式高砲"],weight="牽引約 2.8 噸",crew="8",caliber="2×37mm",
       rng="有效 3,500m",mob="牽引式",armor="—",cap="65 式改良、對空/對地",
       notes="74式雙 37mm 牽引高射砲。",tags=["高射砲","牽引","舊式"],form_zh="牽引式高射砲（雙37mm）",wiki="Type 74 anti-aircraft gun"),
    mk("pll-05","05式 120mm 自行迫榴砲","PLL-05 120mm SP mortar-howitzer","PLL-05","mortar_sp","陸軍",
       aliases=["PLL-05","05式自行迫榴"],weight="約 16.5 噸",crew="5",caliber="120mm 迫榴砲",
       rng="射程 8.5 km（迫擊）/13 km（增程）",mob="ZSL-92 6×6 輪式",armor="裝甲",
       cap="迫擊/直射/榴彈多用途、可射制導砲彈",notes="05式輪式自行迫榴砲，迫擊與榴彈兩用。",
       tags=["自行迫榴","輪式"],form_zh="自行迫榴砲（120mm）",wiki="PLL-05"),
    mk("type-77-hmg","77式 12.7mm 高射機槍","Type 77 heavy MG","Type 77","hmg","通用",cat="weapon",branch_hint="通用",
       aliases=["77式高機"],caliber="12.7×108mm",weight="約 56 kg（含三腳架）",rng="有效 1,600m",
       cap="對空/對地、輕量三腳架",mob="—",notes="77式 12.7mm 高射機槍。",tags=["重機槍","高射"],
       form_zh="12.7mm 高射機槍",wiki="Type 77 heavy machine gun"),
]

# ===== 批次 E10：無人機／巡飛彈 =====
DRONE = [
    mk("asn-301","ASN-301 反輻射無人機","ASN-301 anti-radiation UAV","ASN-301","uav","空軍",cat="weapon",
       aliases=["ASN-301","Harpy 衍生"],rng="航程約 288 km／滯空 4h",caliber="反輻射巡飛",
       cap="被動雷達尋標、攻擊敵防空雷達（Harpy 衍生）",mob="巡飛/俯衝攻擊",branch_hint="空軍",
       notes="ASN-301 反輻射攻擊無人機，壓制敵防空。",tags=["無人機","反輻射"],
       form_zh="反輻射攻擊無人機",wiki="ASN-301"),
    mk("ws-43","WS-43 巡飛彈","WS-43 loitering munition","WS-43","uav","陸軍",cat="weapon",
       aliases=["WS-43"],rng="射程約 60 km／滯空 30 min",caliber="巡飛彈",
       cap="區域巡飛、俯衝攻擊點目標",mob="火箭發射、巡飛",branch_hint="陸軍",
       notes="WS-43 巡飛彈（自殺無人機），火箭砲車發射。",tags=["巡飛彈","自殺無人機"],
       form_zh="巡飛彈（loitering munition）",wiki="WS-43"),
    mk("ch-901","彩虹-901 巡飛彈","CH-901 loitering munition","CH-901","uav","陸軍",cat="weapon",
       aliases=["CH-901"],rng="射程約 15 km／滯空 2h",caliber="巡飛彈",
       cap="偵察/攻擊一體、多聯裝發射",mob="管射巡飛",branch_hint="陸軍",
       notes="彩虹-901 小型巡飛彈，偵打一體。",tags=["巡飛彈","偵打"],
       form_zh="小型巡飛彈",wiki="CASC Rainbow"),
    mk("fh-97","飛鴻-97 忠誠僚機","FH-97 loyal wingman","FH-97","uav","空軍",
       aliases=["FH-97","飛鴻97"],rng="—",caliber="—",
       cap="有人-無人協同、內置彈艙（概念/發展）",mob="噴射匿蹤無人機",branch_hint="空軍",
       notes="飛鴻-97 忠誠僚機概念無人機（航天彩虹）。",tags=["無人機","忠誠僚機"],
       form_zh="忠誠僚機無人機",wiki="FH-97"),
    mk("wz-6","無偵-6 偵察無人機","WZ-6 recon UAV","WZ-6","uav","空軍",
       aliases=["無偵6"],rng="—",caliber="—",cap="戰術/戰役偵察",mob="無人偵察機",branch_hint="空軍",
       notes="無偵-6 偵察無人機（公開資料有限）。",tags=["無人機","偵察"],
       form_zh="偵察無人機",wiki="Guizhou WZ-6"),
    mk("gj-1","攻擊-1 察打無人機","GJ-1 (Wing Loong I mil.)","GJ-1","uav","空軍",cat="weapon",
       aliases=["GJ-1","攻擊1","翼龍軍用"],rng="滯空約 20h",caliber="察打",
       cap="AKD-10／FT 炸彈、偵打一體",mob="中空長航時",branch_hint="空軍",
       notes="攻擊-1 為翼龍-1 的解放軍軍用編號。",tags=["無人機","察打"],
       form_zh="察打一體無人機（攻擊-1）",wiki="CAIG Wing Loong"),
]

# ===== 批次 E11：單兵裝備／後勤 =====
SUPPORT = [
    mk("type-06-armor","06式防彈衣","Type 06 body armor","Type 06","individual","通用",cat="equipment",
       aliases=["06式防彈衣"],cap="模組化防彈插板、防破片/手槍彈",mob="單兵防護",
       notes="06式單兵防彈衣，模組化防護。",tags=["單兵","防護"],form_zh="單兵防彈衣",wiki="",
       sources=[]),
    mk("qgf-02","QGF-02 頭盔","QGF-02 helmet","QGF-02","individual","通用",cat="equipment",
       aliases=["QGF-02"],cap="芳綸複合防彈頭盔",mob="單兵防護",
       notes="QGF-02 芳綸防彈頭盔。",tags=["單兵","頭盔"],form_zh="防彈頭盔",wiki="",sources=[]),
    mk("single-soldier-system","單兵數位化作戰系統","PLA soldier system","Soldier System","individual","通用",cat="equipment",
       aliases=["單兵系統"],cap="頭盔顯示、北斗定位、資料鏈、夜視整合",mob="單兵資訊化",
       notes="解放軍單兵數位化作戰系統（整合定位/通信/夜視）。",tags=["單兵","資訊化"],
       form_zh="單兵數位化系統",wiki="",sources=[]),
    mk("zzc-command","裝甲指揮通信車","Armored command vehicle","ZZC","light_vehicle","陸軍",
       aliases=["指揮車"],crew="指揮/參謀組",cap="C4ISR、資料鏈、野戰指揮所",mob="輪式/履帶裝甲底盤",
       notes="裝甲指揮通信車（型號多樣），營旅級野戰指揮。",tags=["指揮車","通信"],
       form_zh="裝甲指揮通信車（C2）",wiki="",sources=[]),
    mk("sx2306-truck","陝汽 SX2306 越野卡車","Shaanxi SX2306 truck","SX2306","light_vehicle","陸軍",
       aliases=["SX2306","陝汽卡車"],weight="載重約 6–8 噸",cap="部隊/物資運輸、火砲牽引",mob="6×6 越野卡車",
       notes="陝汽 SX2306 系列軍用越野卡車，後勤運輸主力。",tags=["卡車","後勤"],
       form_zh="軍用越野卡車",wiki="",sources=[]),
    mk("field-fuel-truck","野戰油罐車","Field fuel tanker","Fuel Truck","light_vehicle","陸軍",
       aliases=["油罐車"],cap="燃油運輸/野戰加油",mob="卡車底盤",
       notes="野戰油罐/加油車，部隊油料補給。",tags=["後勤","油料"],
       form_zh="野戰油罐/加油車",wiki="",sources=[]),
]

def merge(batch):
    data = json.loads(OUT.read_text(encoding="utf-8")) if OUT.exists() else []
    by = {x["id"]: x for x in data}
    for it in batch:
        by[it["id"]] = it
    out = list(by.values())
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    return len(out), len(batch)

if __name__ == "__main__":
    n = 0
    for name, batch in [("E1 海軍", NAVAL), ("E2 空軍/陸航", AIR), ("E3 陸軍", GROUND),
                        ("E4 雷達/電戰", RADAR), ("E5 飛彈變體", MISSILE), ("E6 步兵武器", INFANTRY),
                        ("E7 海軍2", NAVAL2), ("E8 空軍2", AIR2), ("E9 陸軍2", GROUND2),
                        ("E10 無人機/巡飛彈", DRONE), ("E11 單兵/後勤", SUPPORT)]:
        total, cnt = merge(batch)
        print(f"批次 {name}：{cnt} 筆")
        n = total
    print(f"new_items_extra.json 現有 {n} 筆")
